"use client";
import { useState } from "react";
import { UserPlus } from "lucide-react";
import { Button, Dialog, useToast } from "@/components/ui";
import type { DatabaseAppRole } from "@/types/database";

export function AccountDialog({ schoolId }: { schoolId: string | null }) {
  const { showToast } = useToast(); const [role, setRole] = useState<DatabaseAppRole>("student"); const [busy, setBusy] = useState(false); const [form, setForm] = useState({ firstName: "", lastName: "", login: "", temporaryPassword: "" });
  async function submit(): Promise<void> { if (!schoolId) return; setBusy(true); const prefix = role === "student" ? "s" : role === "parent" ? "f" : "t"; const login = form.login.startsWith(`${prefix}_`) ? form.login : `${prefix}_${form.login}`; const response = await fetch("/api/admin/accounts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, login, roles: [role], schoolId, locale: "ar" }) }); setBusy(false); if (!response.ok) { showToast({ title: "تعذر إنشاء الحساب", tone: "info" }); return; } showToast({ title: "تم إنشاء الحساب", tone: "success" }); window.location.reload(); }
  return <Dialog trigger={<Button><UserPlus size={18} />إنشاء حساب</Button>} title="إنشاء حساب جديد" description="أنشئ الحساب ثم أكمل ملفه وألحقه بالقسم المناسب."><div className="command-form"><label>نوع الحساب<select value={role} onChange={(event) => setRole(event.target.value as DatabaseAppRole)}><option value="student">طالب</option><option value="parent">ولي أمر</option><option value="teacher">أستاذ</option><option value="admin">موظف إداري</option></select></label><div className="form-pair"><label>الاسم<input value={form.firstName} onChange={(event) => setForm((row) => ({ ...row, firstName: event.target.value }))} /></label><label>النسب<input value={form.lastName} onChange={(event) => setForm((row) => ({ ...row, lastName: event.target.value }))} /></label></div><label>اسم الدخول<input dir="ltr" value={form.login} onChange={(event) => setForm((row) => ({ ...row, login: event.target.value }))} /></label><label>كلمة المرور المؤقتة<input dir="ltr" type="password" value={form.temporaryPassword} onChange={(event) => setForm((row) => ({ ...row, temporaryPassword: event.target.value }))} /></label><Button loading={busy} disabled={!schoolId || form.firstName.trim().length < 1 || form.lastName.trim().length < 1 || form.temporaryPassword.length < 10} onClick={() => void submit()}>إنشاء الحساب</Button></div></Dialog>;
}
