"use client";

import { AlertTriangle, BarChart3, History, MailPlus, Send, SlidersHorizontal } from "lucide-react";
import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { Badge, Button, Card, Input, Select, useToast } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import type { DatabaseNotificationChannel, DatabaseNotificationPriority, Json } from "@/types/database";

type Tab = "compose" | "campaigns" | "failures" | "templates" | "stats";
type Campaign = { id: string; title: string; status: string; priority: DatabaseNotificationPriority; estimated_recipients: number; scheduled_at: string | null; created_at: string };
type Delivery = { id: string; channel: DatabaseNotificationChannel; status: string; masked_destination: string | null; attempt_count: number; error_code: string | null; created_at: string };
type Template = { id: string; event_type: string; locale: string; channel: DatabaseNotificationChannel; title_template: string; active: boolean };
const tabs = [{ id: "compose", label: "إنشاء إرسال", icon: MailPlus }, { id: "campaigns", label: "الإرسالات", icon: History }, { id: "failures", label: "الإخفاقات", icon: AlertTriangle }, { id: "templates", label: "القوالب", icon: SlidersHorizontal }, { id: "stats", label: "الإحصاءات", icon: BarChart3 }] satisfies Array<{ id: Tab; label: string; icon: typeof Send }>;

export function AdminCommunicationCenter({ schoolId, classes }: { schoolId: string | null; classes: Array<{ id: string; name: string }> }) {
  const { showToast } = useToast(); const [tab, setTab] = useState<Tab>("compose"); const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [deliveries, setDeliveries] = useState<Delivery[]>([]); const [templates, setTemplates] = useState<Template[]>([]);
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [href, setHref] = useState(""); const [audienceType, setAudienceType] = useState("all"); const [audienceValue, setAudienceValue] = useState(""); const [priority, setPriority] = useState<DatabaseNotificationPriority>("normal"); const [channels, setChannels] = useState<DatabaseNotificationChannel[]>(["in_app"]); const [scheduledAt, setScheduledAt] = useState(""); const [estimate, setEstimate] = useState<number | null>(null); const [confirming, setConfirming] = useState(false); const [busy, setBusy] = useState(false);
  const audience = useMemo<Json>(() => audienceType === "role" ? { type: "role", role: audienceValue } : audienceType === "class" ? { type: "class", class_id: audienceValue } : { type: "all" }, [audienceType, audienceValue]);
  const load = useCallback(async () => { if (!schoolId || process.env.NEXT_PUBLIC_APP_ENV === "test") return; const client = createClient(); const [campaignRows, deliveryRows, templateRows] = await Promise.all([client.from("notification_campaigns").select("id,title,status,priority,estimated_recipients,scheduled_at,created_at").eq("school_id", schoolId).order("created_at", { ascending: false }).limit(100), client.from("notification_deliveries").select("id,channel,status,masked_destination,attempt_count,error_code,created_at").order("created_at", { ascending: false }).limit(200), client.from("notification_templates").select("id,event_type,locale,channel,title_template,active").eq("school_id", schoolId).order("event_type")]); setCampaigns(campaignRows.data ?? []); setDeliveries(deliveryRows.data ?? []); setTemplates(templateRows.data ?? []); }, [schoolId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function preview() { if (!schoolId || !title.trim() || !body.trim() || (audienceType !== "all" && !audienceValue)) return showToast({ title: "أكمل بيانات الإرسال أولا", tone: "info" }); setBusy(true); const result = await createClient().rpc("estimate_notification_audience", { target_school_id: schoolId, target_audience: audience }); setBusy(false); if (result.error) return showToast({ title: "تعذر حساب المستلمين", description: "تحقق من الصلاحيات والمصادقة الإضافية.", tone: "info" }); setEstimate(result.data); setConfirming(true); }
  async function send() { if (!schoolId || estimate === null || channels.length === 0) return; setBusy(true); const result = await createClient().rpc("create_notification_campaign", { target_school_id: schoolId, target_title: title.trim(), target_body: body.trim(), target_href: href.trim(), target_audience: audience, target_channels: channels, target_priority: priority, target_locale: "ar", target_scheduled_at: scheduledAt ? new Date(scheduledAt).toISOString() : new Date().toISOString(), target_expires_at: null }); setBusy(false); if (result.error) return showToast({ title: "تعذر إرسال الإشعار", description: "لم تُرسل أي رسالة. راجع الصلاحيات والبيانات.", tone: "info" }); setTitle(""); setBody(""); setHref(""); setConfirming(false); setEstimate(null); await load(); showToast({ title: scheduledAt ? "تمت جدولة الإرسال" : "تم إنشاء الإرسال", tone: "success" }); }
  function resetPreview() { setEstimate(null); setConfirming(false); }
  function toggleChannel(channel: DatabaseNotificationChannel) { resetPreview(); setChannels((items) => items.includes(channel) ? items.filter((item) => item !== channel) : [...items, channel]); }
  const failed = deliveries.filter((item) => ["failed", "dead_letter"].includes(item.status)); const delivered = deliveries.filter((item) => ["sent", "delivered"].includes(item.status)).length;
  return <section className="admin-communication-center"><header className="communication-hero"><span>مركز الاتصال</span><h1>الإشعارات والإرسالات</h1><p>إرسال واضح، قابل للتتبع، ومحمي بالصلاحيات.</p></header><nav className="communication-tabs" aria-label="أقسام مركز الاتصال">{tabs.map((item) => { const Icon = item.icon; return <button type="button" key={item.id} className={tab === item.id ? "is-active" : undefined} onClick={() => setTab(item.id)}><Icon size={17} />{item.label}</button>; })}</nav>
    {tab === "compose" ? <div className="campaign-compose"><div className="campaign-form"><Input label="العنوان" value={title} maxLength={160} onChange={(event) => { resetPreview(); setTitle(event.target.value); }} /><label className="ui-field"><span className="ui-field__label">النص</span><textarea className="request-details" value={body} maxLength={4000} onChange={(event) => { resetPreview(); setBody(event.target.value); }} /></label><Input label="الرابط داخل المنصة" dir="ltr" value={href} onChange={(event) => { resetPreview(); setHref(event.target.value); }} placeholder="/student/assignments" /><div className="campaign-controls"><Select label="المستلمون" value={audienceType} onChange={(event) => { resetPreview(); setAudienceType(event.target.value); setAudienceValue(""); }}><option value="all">جميع مستخدمي المؤسسة</option><option value="role">حسب الفئة</option><option value="class">حسب القسم</option></Select>{audienceType === "role" ? <Select label="الفئة" value={audienceValue} onChange={(event) => { resetPreview(); setAudienceValue(event.target.value); }}><option value="">اختر</option><option value="student">الطلاب</option><option value="parent">الأسر</option><option value="teacher">الأساتذة</option></Select> : null}{audienceType === "class" ? <Select label="القسم" value={audienceValue} onChange={(event) => { resetPreview(); setAudienceValue(event.target.value); }}><option value="">اختر</option>{classes.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</Select> : null}<Select label="الأولوية" value={priority} onChange={(event) => { resetPreview(); setPriority(event.target.value as DatabaseNotificationPriority); }}><option value="low">منخفضة</option><option value="normal">عادية</option><option value="important">مهمة</option><option value="urgent">مستعجلة</option></Select><Input label="موعد الإرسال" type="datetime-local" value={scheduledAt} onChange={(event) => { resetPreview(); setScheduledAt(event.target.value); }} /></div><fieldset className="channel-picker"><legend>قنوات الإرسال</legend>{([['in_app','داخل التطبيق'],['push','إشعار الجهاز'],['email','البريد الإلكتروني'],['sms','رسالة نصية']] as Array<[DatabaseNotificationChannel,string]>).map(([id, text]) => <label key={id}><input type="checkbox" checked={channels.includes(id)} onChange={() => toggleChannel(id)} />{text}</label>)}</fieldset><Button loading={busy} onClick={() => void preview()}><Send size={18} />معاينة المستلمين</Button></div><Card className="campaign-preview"><h2>المعاينة</h2>{confirming ? <><Badge tone={priority === "urgent" ? "danger" : "brand"}>{estimate} مستلم</Badge><strong>{title}</strong><p>{body}</p><small>{channels.map(channelLabel).join(" · ")}</small><Button loading={busy} onClick={() => void send()}>تأكيد الإرسال</Button></> : <p>لن يتم الإرسال قبل حساب الجمهور والتأكيد.</p>}</Card></div> : null}
    {tab === "campaigns" ? <RecordList empty="لا توجد إرسالات بعد.">{campaigns.map((item) => <article key={item.id}><div><strong>{item.title}</strong><small>{item.estimated_recipients} مستلم · {formatDate(item.scheduled_at ?? item.created_at)}</small></div><Badge tone={item.status === "sent" ? "success" : "neutral"}>{statusLabel(item.status)}</Badge></article>)}</RecordList> : null}
    {tab === "failures" ? <RecordList empty="لا توجد إخفاقات في السجل الحالي.">{failed.map((item) => <article key={item.id}><div><strong>{channelLabel(item.channel)} · {item.masked_destination ?? "وجهة غير متاحة"}</strong><small>{item.error_code ?? "خطأ مزود"} · المحاولة {item.attempt_count}</small></div><Badge tone="danger">{item.status === "dead_letter" ? "تدخل مطلوب" : "ستعاد المحاولة"}</Badge></article>)}</RecordList> : null}
    {tab === "templates" ? <RecordList empty="لا توجد قوالب مخصصة.">{templates.map((item) => <article key={item.id}><div><strong>{item.title_template}</strong><small>{item.event_type} · {item.locale} · {channelLabel(item.channel)}</small></div><Badge tone={item.active ? "success" : "neutral"}>{item.active ? "نشط" : "متوقف"}</Badge></article>)}</RecordList> : null}
    {tab === "stats" ? <div className="communication-stats"><Card><strong>{campaigns.length}</strong><span>إرسال</span></Card><Card><strong>{deliveries.length}</strong><span>محاولة توصيل</span></Card><Card><strong>{delivered}</strong><span>تم بنجاح</span></Card><Card><strong>{failed.length}</strong><span>إخفاق</span></Card></div> : null}</section>;
}
function RecordList({ children, empty }: { children: ReactNode[]; empty: string }) { return <div className="campaign-records">{children.length ? children : <p>{empty}</p>}</div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("ar-MA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function channelLabel(channel: DatabaseNotificationChannel) { return ({ in_app: "داخل التطبيق", push: "الجهاز", email: "البريد", sms: "رسالة نصية", whatsapp: "واتساب" } as const)[channel]; }
function statusLabel(status: string) { return ({ draft: "مسودة", scheduled: "مجدول", processing: "قيد الإرسال", sent: "تم", partially_failed: "تم جزئيا", cancelled: "ملغى" } as Record<string,string>)[status] ?? status; }
