"use client";
import { useState } from "react";
import { AlertTriangle, ArrowLeft, BrainCircuit, Check, Clock3, Search, ShieldAlert } from "lucide-react";
import { Badge, Button, ButtonLink, EmptyState, useToast } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import type { AdminCommandData, CommandTask } from "./models";

export function CommandDashboard({ data }: { data: AdminCommandData }) {
  const [query, setQuery] = useState(""); const [tasks, setTasks] = useState(data.tasks); const { showToast } = useToast();
  const visible = tasks.filter((task) => `${task.title} ${task.reason}`.toLocaleLowerCase("ar").includes(query.toLocaleLowerCase("ar")));
  async function resolve(task: CommandTask): Promise<void> { if (task.source !== "task") return; const { error } = await createClient().rpc("admin_resolve_task", { target_task_id: task.id, target_status: "done" }); if (error) { showToast({ title: "تعذر إغلاق المهمة", tone: "info" }); return; } setTasks((rows) => rows.filter(({ id }) => id !== task.id)); showToast({ title: "تمت معالجة المهمة", tone: "success" }); }
  return <div className="command-page"><header className="command-hero"><div><span>e-Mawahib Command</span><h1>مركز قيادة {data.school?.name ?? "المؤسسة"}</h1><p>ما يحدث اليوم، وما يحتاج قرارا الآن.</p></div><time>اليوم</time></header>
    <section className="command-metrics" aria-label="مؤشرات اليوم">{data.metrics.map((metric) => <article className={metric.tone ? `is-${metric.tone}` : undefined} key={metric.key}><span>{metric.label}</span><strong>{metric.value}</strong></article>)}</section>
    <div className="command-grid"><section className="command-panel command-queue"><div className="command-heading"><div><span>الأولوية الآن</span><h2>معالجة مطلوبة</h2></div><Badge tone={tasks.length ? "danger" : "success"}>{tasks.length}</Badge></div><label className="command-search"><Search size={18} /><input aria-label="البحث في المهام" placeholder="ابحث في المهام" value={query} onChange={(event) => setQuery(event.target.value)} /></label>{visible.length ? <div className="command-task-list">{visible.slice(0, 12).map((task) => <article key={`${task.source}-${task.id}`}><span className={`priority-dot p${task.priority}`} /><div><strong>{task.title}</strong><small>{task.reason}</small></div><Badge tone={task.priority >= 3 ? "danger" : "warning"}>أولوية {task.priority}</Badge>{task.source === "task" ? <Button size="icon" variant="quiet" aria-label="تمت المعالجة" onClick={() => void resolve(task)}><Check size={18} /></Button> : <ButtonLink size="icon" variant="quiet" aria-label="فتح" href={task.href}><ArrowLeft size={18} /></ButtonLink>}</article>)}</div> : <EmptyState title="لا توجد مهام عاجلة" description="كل العناصر المسجلة تمت معالجتها." />}</section>
      <section className="command-panel"><div className="command-heading"><div><span>تحليل قابل للتفسير</span><h2>ذكاء الإدارة</h2></div><BrainCircuit size={23} /></div>{data.insights.length ? <div className="insight-list">{data.insights.map((item) => <ButtonLink variant="quiet" href={item.href} key={item.id}><span className={`insight-icon is-${item.tone}`}>{item.tone === "danger" ? <ShieldAlert /> : <AlertTriangle />}</span><span><strong>{item.title}</strong><small>{item.explanation}</small><b>{item.evidence}</b></span><ArrowLeft size={17} /></ButtonLink>)}</div> : <EmptyState title="لا توجد إشارات مقلقة" description="لم تتجاوز البيانات الحالية حدود التنبيه المحددة." />}</section></div>
    <section className="command-panel"><div className="command-heading"><div><span>النشاط الحقيقي</span><h2>آخر إنجازات الطلاب</h2></div><ButtonLink href="/admin/governance" variant="quiet">كل السجل <ArrowLeft size={16} /></ButtonLink></div>{data.timeline.length ? <div className="command-timeline">{data.timeline.slice(0, 10).map((item) => <article key={item.id}><Clock3 size={17} /><div><strong>{item.title}</strong><small>{item.detail}</small></div><time>{formatTime(item.occurredAt)}</time></article>)}</div> : <EmptyState title="لا توجد أنشطة مسجلة" description="ستظهر الإنجازات فور تسجيلها في مسار التعلم." />}</section>
  </div>;
}
function formatTime(value: string): string { return new Intl.DateTimeFormat("ar-MA", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
