"use client";
import { useMemo, useState } from "react";
import { BookOpenCheck, CalendarDays, FileText, Search, ShieldCheck, UsersRound, WalletCards, Warehouse } from "lucide-react";
import { Badge, ButtonLink, EmptyState } from "@/components/ui";
import type { AdminCommandData, CommandPerson } from "./models";
import { AccountDialog } from "./account-dialog";
import { QuickCreateDialog } from "./quick-create-dialog";

type Domain = "people" | "operations" | "workforce" | "resources" | "communications" | "governance";
export function AdminDomainWorkspace({ domain, data }: { domain: Domain; data: AdminCommandData }) {
  const copy = domainCopy[domain]; const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all");
  return <div className="command-page"><header className="domain-header"><div><span>{copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.description}</p></div>{domain === "people" ? <AccountDialog schoolId={data.school?.id ?? null} /> : domain === "operations" || domain === "resources" || domain === "communications" ? <QuickCreateDialog domain={domain} data={data} /> : <ButtonLink href={copy.actionHref}>{copy.action}</ButtonLink>}</header><div className="domain-toolbar"><label className="command-search"><Search size={18} /><input aria-label="البحث" placeholder="بحث سريع" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select aria-label="التصفية" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">الكل</option>{copy.filters.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div><DomainBody domain={domain} data={data} query={query} filter={filter} /></div>;
}
function DomainBody({ domain, data, query, filter }: { domain: Domain; data: AdminCommandData; query: string; filter: string }) {
  if (domain === "people") return <People data={data} query={query} filter={filter} />;
  if (domain === "operations") return <Operations data={data} query={query} />;
  if (domain === "workforce") return <Workforce data={data} query={query} />;
  if (domain === "resources") return <Resources data={data} />;
  if (domain === "communications") return <Communications data={data} />;
  return <Governance data={data} />;
}
function People({ data, query, filter }: { data: AdminCommandData; query: string; filter: string }) { const rows = useMemo(() => data.people.filter((person) => (filter === "all" || person.role === filter) && person.name.toLocaleLowerCase("ar").includes(query.toLocaleLowerCase("ar"))), [data.people, filter, query]); return rows.length ? <section className="directory-grid">{rows.map((person) => <PersonCard key={person.id} person={person} />)}</section> : <EmptyState title="لا توجد نتائج" description="غيّر البحث أو عامل التصفية." />; }
function PersonCard({ person }: { person: CommandPerson }) { return <article className="directory-card"><div className="directory-head"><span>{person.name.slice(0, 1)}</span><div><strong>{person.name}</strong><small>{roleName(person.role)}{person.className ? ` · ${person.className}` : ""}</small></div><Badge tone={person.status === "active" ? "success" : "warning"}>{statusName(person.status)}</Badge></div>{person.role === "student" ? <dl><div><dt>العمر</dt><dd>{person.age ?? "—"}</dd></div><div><dt>السور</dt><dd>{person.mastered}</dd></div><div><dt>الغياب</dt><dd>{person.absences}</dd></div><div><dt>التأخر</dt><dd>{person.late}</dd></div></dl> : null}<div className="directory-actions"><ButtonLink href={`/admin/people/${person.id}`} variant="secondary">فتح الملف</ButtonLink></div></article>; }
function Operations({ data, query }: { data: AdminCommandData; query: string }) { return <div className="domain-columns"><ListSection title="الأقسام" icon={UsersRound} rows={data.classes.filter((row) => row.name.includes(query)).map((row) => ({ id: row.id, title: row.name, detail: `${row.students} طالب · ${row.teachers} أستاذ · السعة ${row.capacity ?? "—"}` }))} /><ListSection title="تقارير الحصص" icon={BookOpenCheck} rows={data.reports.map((row) => ({ id: row.id, title: `${row.className} · ${row.teacherName}`, detail: `${row.status}${row.incident ? " · يتضمن حادثا" : ""}` }))} /><ListSection title="الحوادث والانضباط" icon={ShieldCheck} rows={data.incidents.map((row) => ({ id: row.id, title: row.summary, detail: `${row.category} · درجة ${row.severity} · ${row.status}` }))} /><ListSection title="السنوات والقاعات" icon={CalendarDays} rows={[...data.years.map((row) => ({ id: row.id, title: row.name, detail: row.active ? "السنة النشطة" : `${row.startsOn} — ${row.endsOn}` })), ...data.rooms.map((row) => ({ id: row.id, title: row.name, detail: `قاعة · السعة ${row.capacity ?? "—"}` }))]} /></div>; }
function Workforce({ data, query }: { data: AdminCommandData; query: string }) { return <div className="domain-columns"><ListSection title="الأساتذة والموظفون" icon={UsersRound} rows={data.people.filter((row) => ["teacher", "admin", "direction"].includes(row.role) && row.name.includes(query)).map((row) => ({ id: row.id, title: row.name, detail: `${roleName(row.role)} · ${statusName(row.status)}` }))} /><ListSection title="الطلبات والإجازات" icon={FileText} rows={data.requests.map((row) => ({ id: row.id, title: row.title, detail: `${row.teacherName} · ${row.kind} · ${row.status}` }))} /><ListSection title="الرواتب" icon={WalletCards} rows={data.salaries.map((row) => ({ id: row.id, title: row.teacherName, detail: `${row.month} · ${row.net} MAD · ${row.status}` }))} /></div>; }
function Resources({ data }: { data: AdminCommandData }) { const income = data.finance.filter(({ direction }) => direction === "income").reduce((sum, row) => sum + row.amount, 0); const expense = data.finance.filter(({ direction }) => direction === "expense").reduce((sum, row) => sum + row.amount, 0); return <><section className="resource-summary"><article><span>المداخيل المسجلة</span><strong>{income.toFixed(2)} MAD</strong></article><article><span>المصاريف المسجلة</span><strong>{expense.toFixed(2)} MAD</strong></article><article><span>الرصيد الحسابي</span><strong>{(income - expense).toFixed(2)} MAD</strong></article></section><div className="domain-columns"><ListSection title="الحركات المالية" icon={WalletCards} rows={data.finance.map((row) => ({ id: row.id, title: row.category, detail: `${row.direction === "income" ? "مدخول" : "مصروف"} · ${row.amount} ${row.currency} · ${row.occurredOn}` }))} /><ListSection title="المعدات والمخزون" icon={Warehouse} rows={data.inventory.map((row) => ({ id: row.id, title: row.name, detail: `${row.category} · ${row.quantity} متوفر · ${row.status}` }))} /></div></>; }
function Communications({ data }: { data: AdminCommandData }) { return <div className="domain-columns"><ListSection title="الإعلانات" icon={FileText} rows={data.announcements.map((row) => ({ id: row.id, title: row.title, detail: `${row.audience} · ${formatDate(row.publishedAt)}` }))} /><ListSection title="الأحداث" icon={CalendarDays} rows={data.events.map((row) => ({ id: row.id, title: row.title, detail: formatDate(row.startsAt) }))} /><ListSection title="الموقع العام" icon={BookOpenCheck} rows={[{ id: "site", title: "الأخبار والإعادات والبرامج", detail: "إدارة المحتوى المنشور والترجمات" }]} /></div>; }
function Governance({ data }: { data: AdminCommandData }) { return <div className="domain-columns"><ListSection title="سجل التدقيق" icon={ShieldCheck} rows={data.audit.map((row) => ({ id: String(row.id), title: row.action, detail: `${row.entityType} · ${formatDate(row.occurredAt)}` }))} /><ListSection title="المهام الإدارية" icon={FileText} rows={data.tasks.map((row) => ({ id: row.id, title: row.title, detail: row.reason }))} /></div>; }
function ListSection({ title, icon: Icon, rows }: { title: string; icon: typeof FileText; rows: Array<{ id: string; title: string; detail: string }> }) { return <section className="command-panel"><div className="command-heading"><h2>{title}</h2><Icon size={21} /></div>{rows.length ? <div className="domain-list">{rows.slice(0, 50).map((row) => <article key={row.id}><div><strong>{row.title}</strong><small>{row.detail}</small></div></article>)}</div> : <EmptyState title="لا توجد بيانات" description="لا توجد سجلات حقيقية في هذا القسم حاليا." />}</section>; }
const domainCopy = { people: { eyebrow: "السجل الموحد", title: "الأشخاص والملفات", description: "الطلاب والأسر والأساتذة والموظفون مع ملفاتهم الرقمية.", action: "إنشاء حساب", actionHref: "/admin#accounts", filters: [{ value: "student", label: "الطلاب" }, { value: "parent", label: "الأسر" }, { value: "teacher", label: "الأساتذة" }, { value: "admin", label: "الإدارة" }] }, operations: { eyebrow: "التشغيل المدرسي", title: "الدراسة والحضور", description: "الأقسام والجداول والقاعات والحضور والتقارير والانضباط.", action: "الموقع العام", actionHref: "/admin/site", filters: [] }, workforce: { eyebrow: "الموارد البشرية", title: "الفريق المهني", description: "الأساتذة والموظفون والطلبات والإجازات والرواتب والوثائق.", action: "عرض الطلبات", actionHref: "/admin/workforce#requests", filters: [] }, resources: { eyebrow: "الاستدامة", title: "المالية والمعدات", description: "حسابات قابلة للتتبع ومخزون واضح دون أرقام تقديرية.", action: "المخزون", actionHref: "/admin/resources#inventory", filters: [] }, communications: { eyebrow: "الصوت الرسمي", title: "التواصل والمحتوى", description: "الرسائل والإعلانات والأحداث والأخبار والإعادات والموقع العام.", action: "إدارة الموقع", actionHref: "/admin/site", filters: [] }, governance: { eyebrow: "المساءلة", title: "الحسابات والصلاحيات والتدقيق", description: "حالات الحسابات والصلاحيات وسجل العمليات للأدوار المصرح لها.", action: "مركز القيادة", actionHref: "/admin", filters: [] } } satisfies Record<Domain, { eyebrow: string; title: string; description: string; action: string; actionHref: string; filters: Array<{ value: string; label: string }> }>;
function roleName(value: string): string { return ({ student: "طالب", parent: "ولي أمر", teacher: "أستاذ", admin: "إدارة", direction: "مديرية" } as Record<string, string>)[value] ?? value; }
function statusName(value: string): string { return ({ active: "نشط", pending: "قيد التفعيل", suspended: "موقوف", archived: "مؤرشف" } as Record<string, string>)[value] ?? value; }
function formatDate(value: string): string { return new Intl.DateTimeFormat("ar-MA", { dateStyle: "medium", timeStyle: value.includes("T") ? "short" : undefined }).format(new Date(value)); }
