(function(){
'use strict';
const api=()=>window.Auth&&Auth.getSupabaseClient?Auth.getSupabaseClient():null;
const err=(e,m)=>{console.error('[AdminData]',e);return {ok:false,error:e&&e.message||m};};
async function audit(action,type,id,oldValues,newValues){const c=api(),s=Auth.getSession&&Auth.getSession();if(!c)return err(null,'Supabase indisponible.');const r=await c.from('admin_audit_logs').insert([{actor_id:s&&s.username||'__admin__',action,entity_type:type,entity_id:String(id),old_values:oldValues||null,new_values:newValues||null}]);return r.error?err(r.error,'Journal non enregistré.'):{ok:true};}
async function getStudentProfile(username){const c=api();if(!c)return err(null,'Supabase indisponible.');const r=await c.from('student_admin_profiles').select('*').eq('username',username).maybeSingle();return r.error?err(r.error,'Profil introuvable.'):{ok:true,data:r.data};}
async function saveStudentProfile(username,values){const c=api();if(!c)return err(null,'Supabase indisponible.');const before=await getStudentProfile(username),row=Object.assign({},values,{username,updated_at:new Date().toISOString()});const r=await c.from('student_admin_profiles').upsert([row]);if(r.error)return err(r.error,'Profil non enregistré.');await audit('student_profile_upsert','student',username,before.data,row);return {ok:true};}
async function listClasses(){const c=api();if(!c)return err(null,'Supabase indisponible.');const r=await c.from('school_classes').select('*').order('name');return r.error?err(r.error,'Classes indisponibles.'):{ok:true,data:r.data||[]};}
async function saveClass(values){const c=api();if(!c)return err(null,'Supabase indisponible.');const row=Object.assign({},values,{updated_at:new Date().toISOString()}),r=await c.from('school_classes').upsert([row]).select().single();if(r.error)return err(r.error,'Classe non enregistrée.');await audit(values.id?'class_update':'class_create','class',r.data.id,null,r.data);return {ok:true,data:r.data};}
async function assignStudents(classId,usernames){const c=api(),rows=(usernames||[]).filter(Boolean).map(student_username=>({class_id:classId,student_username,removed_at:null,assigned_at:new Date().toISOString()}));if(!c)return err(null,'Supabase indisponible.');if(!rows.length)return {ok:true};const r=await c.from('class_students').upsert(rows);if(r.error)return err(r.error,'Affectation impossible.');await audit('students_assign','class',classId,null,{students:usernames});return {ok:true};}
async function sendMessage(payload){const c=api(),s=Auth.getSession&&Auth.getSession();if(!c)return err(null,'Supabase indisponible.');const row={sender_id:s&&s.username||'__admin__',sender_role:s&&s.role||'admin',recipient_id:String(payload.recipient_id||'').trim(),recipient_role:payload.recipient_role||'student',subject:String(payload.subject||'').trim(),content:String(payload.content||'').trim(),parent_message_id:payload.parent_message_id||null};if(!row.recipient_id||!row.content)return {ok:false,error:'المستلم والرسالة مطلوبان.'};const r=await c.from('school_messages').insert([row]).select().single();if(r.error)return err(r.error,'Message non envoyé.');await audit('message_send','message',r.data.id,null,r.data);return {ok:true,data:r.data};}
async function inbox(username){const c=api();if(!c)return err(null,'Supabase indisponible.');const r=await c.from('school_messages').select('*').eq('recipient_id',username).is('archived_at',null).order('created_at',{ascending:false});return r.error?err(r.error,'Boîte indisponible.'):{ok:true,data:r.data||[]};}
async function markRead(id){const c=api();if(!c)return err(null,'Supabase indisponible.');const r=await c.from('school_messages').update({is_read:true,status:'read',read_at:new Date().toISOString()}).eq('id',id);return r.error?err(r.error,'Lecture non enregistrée.'):{ok:true};}
window.AdminData={audit,getStudentProfile,saveStudentProfile,listClasses,saveClass,assignStudents,sendMessage,inbox,markRead};
})();