(function(){
  'use strict';
  const page=document.body.dataset.adminPage||'students';
  const links=[['students','controle-487-eleves.html','👥','الطلاب'],['teachers','controle-487-profs.html','🧑‍🏫','الأساتذة'],['classes','controle-487-classes.html','🏫','الأقسام'],['finance','controle-487-finance.html','💳','المالية'],['stats','controle-487-stats.html','📊','الإحصاءات'],['messages','controle-487-messages.html','✉️','الرسائل']];
  const state={students:[],profs:{},reports:[],finance:[],selectedStudent:'',teacherNotes:{},error:''};
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const arg=value=>esc(String(value??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'"));
  const studentName=item=>`${item?.prenom||''} ${item?.nom||''}`.trim()||item?.username||'';
  const profName=item=>item?.prenom||item?.username||'';
  const profList=()=>Object.values(state.profs||{});
  function uniqueProgress(student){const seen=new Map();Object.entries(student?.progress||{}).forEach(([id,row])=>{const key=Auth.normalizeSurahId?Auth.normalizeSurahId(row?.surah_id||id):String(row?.surah_id||id).replace(/_/g,'-');const previous=seen.get(key);const currentDate=String(row?.completed_at||row?.completedAt||'');const previousDate=String(previous?.completed_at||previous?.completedAt||'');if(!previous||currentDate>=previousDate)seen.set(key,{...row,surahId:key})});return [...seen.values()]}
  const completedCount=student=>uniqueProgress(student).filter(row=>row&&(row.is_completed||row.completed_at||row.completedAt)).length;
  const pendingDuties=student=>(student?.devoirs||[]).filter(row=>row.statut!=='termine').length;
  function money(value){return (Number(value)||0).toLocaleString('fr-MA',{maximumFractionDigits:2})+' DH'}
  function options(items,valueKey,labeler){return items.map(item=>`<option value="${esc(item[valueKey])}">${esc(labeler(item))}</option>`).join('')}

  function layout(){document.getElementById('admin-app').innerHTML=`<div class="admin-shell"><header class="admin-head"><div class="admin-brand"><img src="logo.webp" class="admin-logo" alt=""><div><div class="admin-title">إدارة مواهب المنان</div><div class="admin-subtitle">بيانات مباشرة من المنصة</div></div></div><button class="admin-small danger" onclick="adminLogout()">خروج</button></header><main id="admin-main" class="admin-main"></main></div><nav class="admin-nav" id="admin-nav">${links.map(item=>`<a href="${item[1]}" class="${item[0]===page?'active':''}"><span class="icon">${item[2]}</span><span>${item[3]}</span></a>`).join('')}</nav>`}
  function heading(title,help){return `<h1 class="admin-page-title">${title}</h1><p class="admin-help">${help}</p>${state.error?`<div class="admin-status">${esc(state.error)}</div>`:''}`}
  function kpi(value,label){return `<div class="admin-kpi"><div class="admin-kpi-value">${esc(value)}</div><div class="admin-kpi-label">${label}</div></div>`}
  function empty(text){return `<div class="admin-empty">${text}</div>`}
  async function load(){try{const [students,profs,reports,finance]=await Promise.all([Auth.getAllStudents(),Auth.getProfs(),Auth.getAdminReports(),Auth.getFinanceEntries()]);state.students=Array.isArray(students)?students:[];state.profs=profs||{};state.reports=Array.isArray(reports)?reports:[];state.finance=Array.isArray(finance)?finance:[]}catch(error){state.error='تعذر تحميل بعض البيانات. أعد المحاولة.'}render()}
  function render(){if(page==='students')renderStudents();else if(page==='teachers')renderTeachers();else if(page==='classes')renderClasses();else if(page==='finance')renderFinance();else if(page==='stats')renderStats();else renderMessages()}

  function renderStudents(filter=''){const main=document.getElementById('admin-main');const query=String(filter).trim().toLowerCase();const rows=state.students.filter(item=>(studentName(item)+' '+item.username).toLowerCase().includes(query));main.innerHTML=heading('إدارة الطلاب','الحسابات والتقدم والواجبات من البيانات المسجلة.')+`<div class="admin-toolbar admin-toolbar-compact"><label class="admin-field"><span>بحث</span><input class="admin-control" placeholder="الاسم" value="${esc(filter)}" oninput="renderAdminStudents(this.value)"></label></div><div class="admin-people-grid">${rows.length?rows.map(student=>`<article class="admin-person"><div><div class="admin-row-title">${esc(studentName(student))}</div><div class="admin-row-meta">${esc(student.username)}</div></div><div class="admin-person-stats"><span>${completedCount(student)} سورة</span><span>${pendingDuties(student)} واجب</span><span class="${student.isSuspended?'is-paused':'is-active'}">${student.isSuspended?'موقوف':'نشط'}</span></div><div class="admin-row-actions"><button class="admin-small" onclick="toggleAdminStudent('${arg(student.username)}')">${student.isSuspended?'تفعيل':'إيقاف'}</button><button class="admin-small danger" onclick="deleteAdminStudent('${arg(student.username)}')">حذف</button></div></article>`).join(''):empty('لا يوجد طالب مطابق.')}</div>`}

  function renderTeachers(){const main=document.getElementById('admin-main');const profs=profList();main.innerHTML=heading('إدارة الأساتذة','إضافة أستاذ أو حذف حساب وربطه بقسم.')+`<form class="admin-toolbar" onsubmit="addAdminTeacher(event)"><label class="admin-field"><span>اسم الأستاذ</span><input id="new-prof-name" class="admin-control" required></label><label class="admin-field"><span>القسم</span><input id="new-prof-class" class="admin-control" required></label><label class="admin-field"><span>كلمة المرور</span><input id="new-prof-pass" type="password" dir="ltr" class="admin-control" required></label><button class="admin-action" type="submit">إضافة</button></form><div class="admin-people-grid">${profs.length?profs.map(prof=>`<article class="admin-person"><div><div class="admin-row-title">${esc(profName(prof))}</div><div class="admin-row-meta">${esc(prof.classe||'بدون قسم')}</div></div><div class="admin-person-stats"><span>${(prof.students||[]).length} طالب</span></div><div class="admin-row-actions"><button class="admin-small danger" onclick="deleteAdminTeacher('${arg(prof.username)}')">حذف</button></div></article>`).join(''):empty('لا يوجد أستاذ مسجل.')}</div>`}

  function renderClasses(){const main=document.getElementById('admin-main');const profs=profList();main.innerHTML=heading('إدارة الأقسام','ربط الطلاب بالأساتذة وفق الحسابات الموجودة.')+`<form class="admin-toolbar" onsubmit="assignAdminStudent(event)"><label class="admin-field"><span>الأستاذ والقسم</span><select id="assign-prof" class="admin-control" required><option value="">اختر</option>${options(profs,'username',p=>`${profName(p)} · ${p.classe||''}`)}</select></label><label class="admin-field"><span>الطالب</span><select id="assign-student" class="admin-control" required><option value="">اختر</option>${options(state.students,'username',studentName)}</select></label><button class="admin-action" type="submit">ربط</button></form><div class="admin-list">${profs.length?profs.map(prof=>{const assigned=(prof.students||[]).map(id=>state.students.find(s=>s.username===id)).filter(Boolean);return `<div class="admin-row"><div><div class="admin-row-title">${esc(prof.classe||'بدون قسم')} · ${esc(profName(prof))}</div><div class="admin-row-meta">${assigned.length} طالب</div><div class="admin-row-actions">${assigned.map(student=>`<button class="admin-small" onclick="removeAdminAssignment('${arg(prof.username)}','${arg(student.username)}')">${esc(studentName(student))} ×</button>`).join('')}</div></div></div>`}).join(''):empty('لا يوجد قسم.')}</div>`}

  function paymentRows(){return state.students.map(student=>{const payments=Array.isArray(student.payments)?student.payments:[];const paid=payments.filter(p=>p.status==='payé').reduce((sum,p)=>sum+(Number(p.amount)||0),0);const pending=payments.filter(p=>p.status!=='payé').reduce((sum,p)=>sum+(Number(p.amount)||0),0);return {student,paid,pending,count:payments.length}})}
  function renderFinance(){const main=document.getElementById('admin-main');const rows=paymentRows();const paid=rows.reduce((sum,row)=>sum+row.paid,0);const pending=rows.reduce((sum,row)=>sum+row.pending,0);main.innerHTML=heading('إدارة المالية','المبالغ محسوبة من سجل المدفوعات فقط.')+`<div class="admin-kpis">${kpi(money(paid),'المحصّل')}${kpi(money(pending),'المتبقي')}${kpi(rows.filter(r=>r.count).length,'طلاب لهم سجل')}</div><div class="admin-list">${rows.filter(r=>r.count).length?rows.filter(r=>r.count).map(row=>`<div class="admin-row"><div><div class="admin-row-title">${esc(studentName(row.student))}</div><div class="admin-row-meta">محصّل: ${money(row.paid)} · متبق: ${money(row.pending)} · ${row.count} عملية</div></div></div>`).join(''):empty('لا توجد بيانات مالية مسجلة.')}</div>`}

  function renderStats(){const main=document.getElementById('admin-main');const completed=state.students.reduce((sum,s)=>sum+completedCount(s),0);const duties=state.students.reduce((sum,s)=>sum+pendingDuties(s),0);const suspended=state.students.filter(s=>s.isSuspended).length;main.innerHTML=heading('الإحصاءات','ملخص مباشر دون تقديرات أو بيانات افتراضية.')+`<div class="admin-kpis">${kpi(state.students.length,'الطلاب')}${kpi(profList().length,'الأساتذة')}${kpi(completed,'السور المكتملة')}${kpi(duties,'الواجبات المفتوحة')}${kpi(suspended,'الحسابات الموقوفة')}${kpi(state.reports.length,'رسائل الأساتذة')}</div>`}

  function renderMessages(){const main=document.getElementById('admin-main');main.innerHTML=heading('الرسائل','الرسائل الواردة من الأساتذة وإرسال رسالة لطالب.')+`<form class="admin-toolbar" onsubmit="sendAdminStudentMessage(event)"><label class="admin-field"><span>الطالب</span><select id="message-student" class="admin-control" required><option value="">اختر</option>${options(state.students,'username',studentName)}</select></label><label class="admin-field"><span>الرسالة</span><textarea id="message-text" class="admin-control" required></textarea></label><button class="admin-action" type="submit">إرسال</button></form><div class="admin-list"><div class="admin-row-title">الرسائل الواردة</div>${state.reports.length?state.reports.slice(0,30).map(report=>`<div class="admin-row"><div><div class="admin-row-title">${esc(report.profName||'أستاذ')} · ${esc(report.classe||'')}</div><div class="admin-row-meta">${esc(report.category||'متابعة')} · ${esc(report.date||'')}</div><div class="admin-row-meta">${esc(report.text||'')}</div></div></div>`).join(''):empty('لا توجد رسائل واردة.')}</div>`}

  async function reload(message){await load();if(message)toast(message)}
  function toast(text){const node=document.createElement('div');node.className='admin-status';node.style.cssText='position:fixed;z-index:200;top:14px;left:50%;transform:translateX(-50%);background:#124c35;color:#fff';node.textContent=text;document.body.appendChild(node);setTimeout(()=>node.remove(),2200)}
  function initNav(){const nav=document.getElementById('admin-nav');let last=scrollY;addEventListener('scroll',()=>{const y=scrollY;if(Math.abs(y-last)<5)return;nav.classList.toggle('nav-scroll-hidden',y>last&&y>80);last=y},{passive:true})}

  window.renderAdminStudents=renderStudents;
  window.adminLogout=()=>{Auth.logout();location.replace('login.html')};
  window.toggleAdminStudent=async username=>{await Auth.toggleSuspension(username);await reload('تم تحديث الحساب')};
  window.deleteAdminStudent=async username=>{if(!confirm('حذف الطالب وكل بياناته؟'))return;await Auth.deleteStudent(username);await reload('تم حذف الطالب')};
  window.addAdminTeacher=async event=>{event.preventDefault();const result=await Auth.registerProf(document.getElementById('new-prof-name').value,document.getElementById('new-prof-class').value,document.getElementById('new-prof-pass').value);if(result.ok)await reload('تمت إضافة الأستاذ');else toast(result.error||'تعذر الإضافة')};
  window.deleteAdminTeacher=async username=>{if(!confirm('حذف حساب الأستاذ؟'))return;await Auth.deleteProf(username);await reload('تم حذف الأستاذ')};
  window.assignAdminStudent=async event=>{event.preventDefault();await Auth.assignStudentToProf(document.getElementById('assign-prof').value,document.getElementById('assign-student').value);await reload('تم ربط الطالب')};
  window.removeAdminAssignment=async(prof,student)=>{await Auth.removeStudentFromProf(prof,student);await reload('تم فك الارتباط')};
  window.sendAdminStudentMessage=async event=>{event.preventDefault();await Auth.sendMessage(document.getElementById('message-student').value,document.getElementById('message-text').value.trim());document.getElementById('message-text').value='';toast('تم إرسال الرسالة')};
  layout();initNav();load();
})();
