/**
 * =========================================================
 *  REGISTRE CENTRAL — منصة دار القرآن
 * =========================================================
 *  Pour ajouter une nouvelle sourate :
 *  1. Crée son fichier HTML  (ex: Al_Kawthar.html)
 *  2. Ajoute une entrée ici avec  available: true
 *  C'est tout — l'index se met à jour automatiquement.
 * =========================================================
 */

const SURAH_REGISTRY = [
  {
    "id": "al-mulk",
    "num": 67,
    "nameAr": "سُورَةُ المُلۡكِ",
    "nameFr": "La Royauté",
    "ayat": 30,
    "parts": 4,
    "type": "مكية",
    "color": "#334155",
    "emoji": "👑",
    "file": "surah-al-mulk.html",
    "available": true
  },
  {
    "id": "al-qalam",
    "num": 68,
    "nameAr": "سُورَةُ القَلَمِ",
    "nameFr": "La Plume",
    "ayat": 52,
    "parts": 6,
    "type": "مكية",
    "color": "#4338ca",
    "emoji": "✒️",
    "file": "surah-al-qalam.html",
    "available": true
  },
  {
    "id": "al-haqqa",
    "num": 69,
    "nameAr": "سُورَةُ الحَاقَّةِ",
    "nameFr": "L'Inévitable",
    "ayat": 52,
    "parts": 6,
    "type": "مكية",
    "color": "#be123c",
    "emoji": "⚖️",
    "file": "surah-al-haqqa.html",
    "available": true
  },
  {
    "id": "al-maarij",
    "num": 70,
    "nameAr": "سُورَةُ المَعَارِجِ",
    "nameFr": "Les Voies d'Ascension",
    "ayat": 44,
    "parts": 5,
    "type": "مكية",
    "color": "#7c2d12",
    "emoji": "🪜",
    "file": "surah-al-maarij.html",
    "available": true
  },
  {
    "id": "nuh",
    "num": 71,
    "nameAr": "سُورَةُ نُوحٍ",
    "nameFr": "Noé",
    "ayat": 28,
    "parts": 4,
    "type": "مكية",
    "color": "#0369a1",
    "emoji": "🌊",
    "file": "surah-nuh.html",
    "available": true
  },
  {
    "id": "al-jinn",
    "num": 72,
    "nameAr": "سُورَةُ الجِنِّ",
    "nameFr": "Les Djinns",
    "ayat": 28,
    "parts": 4,
    "type": "مكية",
    "color": "#581c87",
    "emoji": "🌌",
    "file": "surah-al-jinn.html",
    "available": true
  },
  {
    "id": "al-muzzammil",
    "num": 73,
    "nameAr": "سُورَةُ المُزَّمِّلِ",
    "nameFr": "L'Enveloppé",
    "ayat": 20,
    "parts": 3,
    "type": "مكية",
    "color": "#1e3a8a",
    "emoji": "🌙",
    "file": "surah-al-muzzammil.html",
    "available": true
  },
  {
    "id": "al-muddaththir",
    "num": 74,
    "nameAr": "سُورَةُ المُدَّثِّرِ",
    "nameFr": "Le Revêtu d'un Manteau",
    "ayat": 56,
    "parts": 6,
    "type": "مكية",
    "color": "#9a3412",
    "emoji": "🧥",
    "file": "surah-al-muddaththir.html",
    "available": true
  },
  {
    "id": "al-qiyama",
    "num": 75,
    "nameAr": "سُورَةُ القِيَامَةِ",
    "nameFr": "La Résurrection",
    "ayat": 40,
    "parts": 5,
    "type": "مكية",
    "color": "#111827",
    "emoji": "⏳",
    "file": "surah-al-qiyama.html",
    "available": true
  },
  {
    "id": "al-insan",
    "num": 76,
    "nameAr": "سُورَةُ الإِنسَانِ",
    "nameFr": "L'Homme",
    "ayat": 31,
    "parts": 5,
    "type": "مدنية",
    "color": "#0f766e",
    "emoji": "🤲",
    "file": "surah-al-insan.html",
    "available": true
  },
  {
    "id": "al-mursalat",
    "num": 77,
    "nameAr": "سُورَةُ المُرۡسَلَاتِ",
    "nameFr": "Les Envoyés",
    "ayat": 50,
    "parts": 6,
    "type": "مكية",
    "color": "#0e7490",
    "emoji": "💨",
    "file": "surah-al-mursalat.html",
    "available": true
  },
  {
    "id": "an-naba",
    "num": 78,
    "nameAr": "سُورَةُ النَّبَإِ",
    "nameFr": "La Nouvelle",
    "ayat": 40,
    "parts": 5,
    "type": "مكية",
    "color": "#92400e",
    "emoji": "📰",
    "file": "surah-an-naba.html",
    "available": true
  },
  {
    "id": "an-naziat",
    "num": 79,
    "nameAr": "سُورَةُ النَّازِعَاتِ",
    "nameFr": "Les Anges qui Arrachent",
    "ayat": 46,
    "parts": 6,
    "type": "مكية",
    "color": "#7f1d1d",
    "emoji": "⚡",
    "file": "surah-an-naziat.html",
    "available": true
  },
  {
    "id": "abasa",
    "num": 80,
    "nameAr": "سُورَةُ عَبَسَ",
    "nameFr": "Il s'est Renfrogné",
    "ayat": 42,
    "parts": 5,
    "type": "مكية",
    "color": "#365314",
    "emoji": "🌿",
    "file": "surah-abasa.html",
    "available": true
  },
  {
    "id": "at-takwir",
    "num": 81,
    "nameAr": "سُورَةُ التَّكۡوِيرِ",
    "nameFr": "L'Obscurcissement",
    "ayat": 29,
    "parts": 4,
    "type": "مكية",
    "color": "#713f12",
    "emoji": "☀️",
    "file": "surah-at-takwir.html",
    "available": true
  },
  {
    "id": "al-infitar",
    "num": 82,
    "nameAr": "سُورَةُ الانفِطَارِ",
    "nameFr": "La Rupture",
    "ayat": 19,
    "parts": 3,
    "type": "مكية",
    "color": "#1d4ed8",
    "emoji": "🌤️",
    "file": "surah-al-infitar.html",
    "available": true
  },
  {
    "id": "al-mutaffifin",
    "num": 83,
    "nameAr": "سُورَةُ المُطَفِّفِينَ",
    "nameFr": "Les Fraudeurs",
    "ayat": 36,
    "parts": 5,
    "type": "مكية",
    "color": "#854d0e",
    "emoji": "⚖️",
    "file": "surah-al-mutaffifin.html",
    "available": true
  },
  {
    "id": "al-inshiqaq",
    "num": 84,
    "nameAr": "سُورَةُ الانشِقَاقِ",
    "nameFr": "La Déchirure",
    "ayat": 25,
    "parts": 4,
    "type": "مكية",
    "color": "#6d28d9",
    "emoji": "🌘",
    "file": "surah-al-inshiqaq.html",
    "available": true
  },
  {
    "id": "al-buruj",
    "num": 85,
    "nameAr": "سُورَةُ البُرُوجِ",
    "nameFr": "Les Constellations",
    "ayat": 22,
    "parts": 4,
    "type": "مكية",
    "color": "#1e40af",
    "emoji": "✨",
    "file": "surah-al-buruj.html",
    "available": true
  },
  {
    "id": "at-tariq",
    "num": 86,
    "nameAr": "سُورَةُ الطَّارِقِ",
    "nameFr": "L'Astre Nocturne",
    "ayat": 17,
    "parts": 3,
    "type": "مكية",
    "color": "#0f172a",
    "emoji": "🌟",
    "file": "surah-at-tariq.html",
    "available": true
  },
  {
    "id": "al-ala",
    "num": 87,
    "nameAr": "سُورَةُ الأَعۡلَىٰ",
    "nameFr": "Le Très-Haut",
    "ayat": 19,
    "parts": 3,
    "type": "مكية",
    "color": "#047857",
    "emoji": "⬆️",
    "file": "surah-al-ala.html",
    "available": true
  },
  {
    "id": "al-ghashiya",
    "num": 88,
    "nameAr": "سُورَةُ الغَاشِيَةِ",
    "nameFr": "L'Enveloppante",
    "ayat": 26,
    "parts": 4,
    "type": "مكية",
    "color": "#b45309",
    "emoji": "🌫️",
    "file": "surah-al-ghashiya.html",
    "available": true
  },
  {
    "id": "al-fajr",
    "num": 89,
    "nameAr": "سُورَةُ الفَجۡرِ",
    "nameFr": "L'Aube",
    "ayat": 30,
    "parts": 4,
    "type": "مكية",
    "color": "#ea580c",
    "emoji": "🌅",
    "file": "surah-al-fajr.html",
    "available": true
  },
  {
    "id": "al-balad",
    "num": 90,
    "nameAr": "سُورَةُ البَلَدِ",
    "nameFr": "La Cité",
    "ayat": 20,
    "parts": 3,
    "type": "مكية",
    "color": "#78350f",
    "emoji": "🏙️",
    "file": "surah-al-balad.html",
    "available": true
  },
  {
    "id": "ash-shams",
    "num": 91,
    "nameAr": "سُورَةُ الشَّمۡسِ",
    "nameFr": "Le Soleil",
    "ayat": 15,
    "parts": 3,
    "type": "مكية",
    "color": "#ca8a04",
    "emoji": "☀️",
    "file": "surah-ash-shams.html",
    "available": true
  },
  {
    "id": "al-layl",
    "num": 92,
    "nameAr": "سُورَةُ اللَّيۡلِ",
    "nameFr": "La Nuit",
    "ayat": 21,
    "parts": 4,
    "type": "مكية",
    "color": "#312e81",
    "emoji": "🌃",
    "file": "surah-al-layl.html",
    "available": true
  },
  {
    "id": "ad-duha",
    "num": 93,
    "nameAr": "سُورَةُ الضُّحَىٰ",
    "nameFr": "Le Jour Montant",
    "ayat": 11,
    "parts": 2,
    "type": "مكية",
    "color": "#d97706",
    "emoji": "🌤️",
    "file": "surah-ad-duha.html",
    "available": true
  },
  {
    "id": "ash-sharh",
    "num": 94,
    "nameAr": "سُورَةُ الشَّرۡحِ",
    "nameFr": "L'Ouverture",
    "ayat": 8,
    "parts": 2,
    "type": "مكية",
    "color": "#059669",
    "emoji": "🌱",
    "file": "surah-ash-sharh.html",
    "available": true
  },
  {
    "id": "al-tin",
    "num": 95,
    "nameAr": "سُورَةُ التِّينِ",
    "nameFr": "Le Figuier",
    "ayat": 8,
    "parts": 2,
    "type": "مكية",
    "color": "#4A148C",
    "emoji": "🌿",
    "file": "Al_Tin.html",
    "available": true
  },
  {
    "id": "al-alaq",
    "num": 96,
    "nameAr": "سُورَةُ العَلَقِ",
    "nameFr": "L'Adhérence",
    "ayat": 19,
    "parts": 3,
    "type": "مكية",
    "color": "#059669",
    "emoji": "📖",
    "file": "Al_Alaq.html",
    "available": true
  },
  {
    "id": "al-qadr",
    "num": 97,
    "nameAr": "سُورَةُ القَدۡرِ",
    "nameFr": "La Nuit du Destin",
    "ayat": 5,
    "parts": 1,
    "type": "مكية",
    "color": "#1e40af",
    "emoji": "🌙",
    "file": "al_kadr.html",
    "available": true
  },
  {
    "id": "al-bayyina",
    "num": 98,
    "nameAr": "سُورَةُ البَيِّنَةِ",
    "nameFr": "La Preuve",
    "ayat": 8,
    "parts": 2,
    "type": "مدنية",
    "color": "#b45309",
    "emoji": "📜",
    "file": "bayina.html",
    "available": true
  },
  {
    "id": "al-zalzala",
    "num": 99,
    "nameAr": "سُورَةُ الزَّلۡزَلَةِ",
    "nameFr": "Le Séisme",
    "ayat": 8,
    "parts": 2,
    "type": "مدنية",
    "color": "#be123c",
    "emoji": "⚡",
    "file": "surah-zalzalah.html",
    "available": true
  },
  {
    "id": "al-adiyat",
    "num": 100,
    "nameAr": "سُورَةُ العَادِيَاتِ",
    "nameFr": "Les Coursiers",
    "ayat": 11,
    "parts": 2,
    "type": "مكية",
    "color": "#0e7490",
    "emoji": "⚔️",
    "file": "surah-adiyat.html",
    "available": true
  },
  {
    "id": "al-qaria",
    "num": 101,
    "nameAr": "سُورَةُ القَارِعَةِ",
    "nameFr": "Le Fracas",
    "ayat": 11,
    "parts": 2,
    "type": "مكية",
    "color": "#7c3aed",
    "emoji": "🌪️",
    "file": "qaria.html",
    "available": true
  },
  {
    "id": "al-takathur",
    "num": 102,
    "nameAr": "سُورَةُ التَّكَاثُرِ",
    "nameFr": "L'Accumulation",
    "ayat": 8,
    "parts": 2,
    "type": "مكية",
    "color": "#065f46",
    "emoji": "💰",
    "file": "surah-takathur.html",
    "available": true
  },
  {
    "id": "al-asr",
    "num": 103,
    "nameAr": "سُورَةُ العَصۡرِ",
    "nameFr": "Le Temps",
    "ayat": 3,
    "parts": 1,
    "type": "مكية",
    "color": "#92400e",
    "emoji": "⏳",
    "file": "surah-asr.html",
    "available": true
  },
  {
    "id": "al-humaza",
    "num": 104,
    "nameAr": "سُورَةُ الهُمَزَةِ",
    "nameFr": "Le Calomniateur",
    "ayat": 9,
    "parts": 2,
    "type": "مكية",
    "color": "#3f3f46",
    "emoji": "⚠️",
    "file": "surah-humaza.html",
    "available": true
  },
  {
    "id": "al-fil",
    "num": 105,
    "nameAr": "سُورَةُ الفِيلِ",
    "nameFr": "L'Éléphant",
    "ayat": 5,
    "parts": 1,
    "type": "مكية",
    "color": "#6b7280",
    "emoji": "🏔️",
    "file": "fil.html",
    "available": true
  },
  {
    "id": "quraysh",
    "num": 106,
    "nameAr": "سُورَةُ قُرَيۡشٍ",
    "nameFr": "Les Qoraïchites",
    "ayat": 4,
    "parts": 1,
    "type": "مكية",
    "color": "#78350f",
    "emoji": "🕋",
    "file": "quraysh.html",
    "available": true
  },
  {
    "id": "al-maun",
    "num": 107,
    "nameAr": "سُورَةُ المَاعُونِ",
    "nameFr": "L'Ustensile",
    "ayat": 7,
    "parts": 1,
    "type": "مكية",
    "color": "#134e4a",
    "emoji": "🕌",
    "file": "surah-al-maun.html",
    "available": true
  },
  {
    "id": "al-kawthar",
    "num": 108,
    "nameAr": "سُورَةُ الكَوۡثَرِ",
    "nameFr": "L'Abondance",
    "ayat": 3,
    "parts": 1,
    "type": "مكية",
    "color": "#1e3a5f",
    "emoji": "💧",
    "file": "surah-al-kawthar.html",
    "available": true
  },
  {
    "id": "al-kafirun",
    "num": 109,
    "nameAr": "سُورَةُ الكَافِرُونَ",
    "nameFr": "Les Mécréants",
    "ayat": 6,
    "parts": 1,
    "type": "مكية",
    "color": "#3b0764",
    "emoji": "🕊️",
    "file": "surah-al-kafirun.html",
    "available": true
  },
  {
    "id": "al-nasr",
    "num": 110,
    "nameAr": "سُورَةُ النَّصۡرِ",
    "nameFr": "Le Secours",
    "ayat": 3,
    "parts": 1,
    "type": "مدنية",
    "color": "#14532d",
    "emoji": "🏆",
    "file": "surah-al-nasr.html",
    "available": true
  },
  {
    "id": "al-masad",
    "num": 111,
    "nameAr": "سُورَةُ المَسَدِ",
    "nameFr": "Les Fibres",
    "ayat": 5,
    "parts": 1,
    "type": "مكية",
    "color": "#7f1d1d",
    "emoji": "🔥",
    "file": "surah-al-masad.html",
    "available": true
  },
  {
    "id": "al-ikhlas",
    "num": 112,
    "nameAr": "سُورَةُ الإِخۡلَاصِ",
    "nameFr": "La Pureté",
    "ayat": 4,
    "parts": 1,
    "type": "مكية",
    "color": "#1e3a8a",
    "emoji": "✨",
    "file": "surah-al-ikhlas.html",
    "available": true
  },
  {
    "id": "al-falaq",
    "num": 113,
    "nameAr": "سُورَةُ الفَلَقِ",
    "nameFr": "L'Aube",
    "ayat": 5,
    "parts": 1,
    "type": "مكية",
    "color": "#451a03",
    "emoji": "🌅",
    "file": "surah-al-falaq.html",
    "available": true
  },
  {
    "id": "al-nas",
    "num": 114,
    "nameAr": "سُورَةُ النَّاسِ",
    "nameFr": "Les Hommes",
    "ayat": 6,
    "parts": 1,
    "type": "مكية",
    "color": "#0c4a6e",
    "emoji": "🌍",
    "file": "surah-al-nas.html",
    "available": true
  }
];
