/**
 * =========================================================
 *  REGISTRE CENTRAL — منصة دار القرآن
 * =========================================================
 *  Ce fichier alimente automatiquement le dashboard eleve.
 *  Toutes les sourates du Coran sont disponibles.
 * =========================================================
 */

const SURAH_REGISTRY = [
  {
    "id": "al-fatihah",
    "num": 1,
    "nameAr": "سُورَةُ ٱلْفَاتِحَةِ",
    "nameFr": "Al-Faatiha",
    "ayat": 7,
    "parts": 1,
    "type": "مكية",
    "color": "#334155",
    "emoji": "📖",
    "file": "surah-al-fatihah.html",
    "available": true
  },
  {
    "id": "al-baqarah",
    "num": 2,
    "nameAr": "سُورَةُ البَقَرَةِ",
    "nameFr": "Al-Baqara",
    "ayat": 286,
    "parts": 10,
    "type": "مدنية",
    "color": "#4338ca",
    "emoji": "🎧",
    "file": "surah-al-baqarah.html",
    "available": true
  },
  {
    "id": "ali-imran",
    "num": 3,
    "nameAr": "سُورَةُ آلِ عِمۡرَانَ",
    "nameFr": "Aal-i-Imraan",
    "ayat": 200,
    "parts": 10,
    "type": "مدنية",
    "color": "#be123c",
    "emoji": "🌙",
    "file": "surah-ali-imran.html",
    "available": true
  },
  {
    "id": "an-nisa",
    "num": 4,
    "nameAr": "سُورَةُ النِّسَاءِ",
    "nameFr": "An-Nisaa",
    "ayat": 176,
    "parts": 8,
    "type": "مدنية",
    "color": "#7c2d12",
    "emoji": "✨",
    "file": "surah-an-nisa.html",
    "available": true
  },
  {
    "id": "al-maidah",
    "num": 5,
    "nameAr": "سُورَةُ المَائـِدَةِ",
    "nameFr": "Al-Maaida",
    "ayat": 120,
    "parts": 6,
    "type": "مدنية",
    "color": "#0369a1",
    "emoji": "⚡",
    "file": "surah-al-maidah.html",
    "available": true
  },
  {
    "id": "al-anam",
    "num": 6,
    "nameAr": "سُورَةُ الأَنۡعَامِ",
    "nameFr": "Al-An'aam",
    "ayat": 165,
    "parts": 8,
    "type": "مكية",
    "color": "#581c87",
    "emoji": "🌿",
    "file": "surah-al-anam.html",
    "available": true
  },
  {
    "id": "al-araf",
    "num": 7,
    "nameAr": "سُورَةُ الأَعۡرَافِ",
    "nameFr": "Al-A'raaf",
    "ayat": 206,
    "parts": 10,
    "type": "مكية",
    "color": "#1e3a8a",
    "emoji": "🕌",
    "file": "surah-al-araf.html",
    "available": true
  },
  {
    "id": "al-anfal",
    "num": 8,
    "nameAr": "سُورَةُ الأَنفَالِ",
    "nameFr": "Al-Anfaal",
    "ayat": 75,
    "parts": 5,
    "type": "مدنية",
    "color": "#9a3412",
    "emoji": "🏆",
    "file": "surah-al-anfal.html",
    "available": true
  },
  {
    "id": "at-tawbah",
    "num": 9,
    "nameAr": "سُورَةُ التَّوۡبَةِ",
    "nameFr": "At-Tawba",
    "ayat": 129,
    "parts": 8,
    "type": "مدنية",
    "color": "#111827",
    "emoji": "💡",
    "file": "surah-at-tawbah.html",
    "available": true
  },
  {
    "id": "yunus",
    "num": 10,
    "nameAr": "سُورَةُ يُونُسَ",
    "nameFr": "Yunus",
    "ayat": 109,
    "parts": 6,
    "type": "مكية",
    "color": "#0f766e",
    "emoji": "🎯",
    "file": "surah-yunus.html",
    "available": true
  },
  {
    "id": "hud",
    "num": 11,
    "nameAr": "سُورَةُ هُودٍ",
    "nameFr": "Hud",
    "ayat": 123,
    "parts": 8,
    "type": "مكية",
    "color": "#0e7490",
    "emoji": "📖",
    "file": "surah-hud.html",
    "available": true
  },
  {
    "id": "yusuf",
    "num": 12,
    "nameAr": "سُورَةُ يُوسُفَ",
    "nameFr": "Yusuf",
    "ayat": 111,
    "parts": 6,
    "type": "مكية",
    "color": "#92400e",
    "emoji": "🎧",
    "file": "surah-yusuf.html",
    "available": true
  },
  {
    "id": "ar-rad",
    "num": 13,
    "nameAr": "سُورَةُ الرَّعۡدِ",
    "nameFr": "Ar-Ra'd",
    "ayat": 43,
    "parts": 4,
    "type": "مدنية",
    "color": "#7f1d1d",
    "emoji": "🌙",
    "file": "surah-ar-rad.html",
    "available": true
  },
  {
    "id": "ibrahim",
    "num": 14,
    "nameAr": "سُورَةُ إِبۡرَاهِيمَ",
    "nameFr": "Ibrahim",
    "ayat": 52,
    "parts": 5,
    "type": "مكية",
    "color": "#365314",
    "emoji": "✨",
    "file": "surah-ibrahim.html",
    "available": true
  },
  {
    "id": "al-hijr",
    "num": 15,
    "nameAr": "سُورَةُ الحِجۡرِ",
    "nameFr": "Al-Hijr",
    "ayat": 99,
    "parts": 6,
    "type": "مكية",
    "color": "#713f12",
    "emoji": "⚡",
    "file": "surah-al-hijr.html",
    "available": true
  },
  {
    "id": "an-nahl",
    "num": 16,
    "nameAr": "سُورَةُ النَّحۡلِ",
    "nameFr": "An-Nahl",
    "ayat": 128,
    "parts": 8,
    "type": "مكية",
    "color": "#1d4ed8",
    "emoji": "🌿",
    "file": "surah-an-nahl.html",
    "available": true
  },
  {
    "id": "al-isra",
    "num": 17,
    "nameAr": "سُورَةُ الإِسۡرَاءِ",
    "nameFr": "Al-Israa",
    "ayat": 111,
    "parts": 6,
    "type": "مكية",
    "color": "#854d0e",
    "emoji": "🕌",
    "file": "surah-al-isra.html",
    "available": true
  },
  {
    "id": "al-kahf",
    "num": 18,
    "nameAr": "سُورَةُ الكَهۡفِ",
    "nameFr": "Al-Kahf",
    "ayat": 110,
    "parts": 6,
    "type": "مكية",
    "color": "#6d28d9",
    "emoji": "🏆",
    "file": "surah-al-kahf.html",
    "available": true
  },
  {
    "id": "maryam",
    "num": 19,
    "nameAr": "سُورَةُ مَرۡيَمَ",
    "nameFr": "Maryam",
    "ayat": 98,
    "parts": 6,
    "type": "مكية",
    "color": "#1e40af",
    "emoji": "💡",
    "file": "surah-maryam.html",
    "available": true
  },
  {
    "id": "taha",
    "num": 20,
    "nameAr": "سُورَةُ طه",
    "nameFr": "Taa-Haa",
    "ayat": 135,
    "parts": 8,
    "type": "مكية",
    "color": "#0f172a",
    "emoji": "🎯",
    "file": "surah-taha.html",
    "available": true
  },
  {
    "id": "al-anbiya",
    "num": 21,
    "nameAr": "سُورَةُ الأَنبِيَاءِ",
    "nameFr": "Al-Anbiyaa",
    "ayat": 112,
    "parts": 6,
    "type": "مكية",
    "color": "#047857",
    "emoji": "📖",
    "file": "surah-al-anbiya.html",
    "available": true
  },
  {
    "id": "al-hajj",
    "num": 22,
    "nameAr": "سُورَةُ الحَجِّ",
    "nameFr": "Al-Hajj",
    "ayat": 78,
    "parts": 5,
    "type": "مدنية",
    "color": "#b45309",
    "emoji": "🎧",
    "file": "surah-al-hajj.html",
    "available": true
  },
  {
    "id": "al-muminun",
    "num": 23,
    "nameAr": "سُورَةُ المُؤۡمِنُونَ",
    "nameFr": "Al-Muminoon",
    "ayat": 118,
    "parts": 6,
    "type": "مكية",
    "color": "#ea580c",
    "emoji": "🌙",
    "file": "surah-al-muminun.html",
    "available": true
  },
  {
    "id": "an-nur",
    "num": 24,
    "nameAr": "سُورَةُ النُّورِ",
    "nameFr": "An-Noor",
    "ayat": 64,
    "parts": 5,
    "type": "مدنية",
    "color": "#78350f",
    "emoji": "✨",
    "file": "surah-an-nur.html",
    "available": true
  },
  {
    "id": "al-furqan",
    "num": 25,
    "nameAr": "سُورَةُ الفُرۡقَانِ",
    "nameFr": "Al-Furqaan",
    "ayat": 77,
    "parts": 5,
    "type": "مكية",
    "color": "#ca8a04",
    "emoji": "⚡",
    "file": "surah-al-furqan.html",
    "available": true
  },
  {
    "id": "ash-shuara",
    "num": 26,
    "nameAr": "سُورَةُ الشُّعَرَاءِ",
    "nameFr": "Ash-Shu'araa",
    "ayat": 227,
    "parts": 10,
    "type": "مكية",
    "color": "#312e81",
    "emoji": "🌿",
    "file": "surah-ash-shuara.html",
    "available": true
  },
  {
    "id": "an-naml",
    "num": 27,
    "nameAr": "سُورَةُ النَّمۡلِ",
    "nameFr": "An-Naml",
    "ayat": 93,
    "parts": 6,
    "type": "مكية",
    "color": "#d97706",
    "emoji": "🕌",
    "file": "surah-an-naml.html",
    "available": true
  },
  {
    "id": "al-qasas",
    "num": 28,
    "nameAr": "سُورَةُ القَصَصِ",
    "nameFr": "Al-Qasas",
    "ayat": 88,
    "parts": 6,
    "type": "مكية",
    "color": "#059669",
    "emoji": "🏆",
    "file": "surah-al-qasas.html",
    "available": true
  },
  {
    "id": "al-ankabut",
    "num": 29,
    "nameAr": "سُورَةُ العَنكَبُوتِ",
    "nameFr": "Al-Ankaboot",
    "ayat": 69,
    "parts": 5,
    "type": "مكية",
    "color": "#134e4a",
    "emoji": "💡",
    "file": "surah-al-ankabut.html",
    "available": true
  },
  {
    "id": "ar-rum",
    "num": 30,
    "nameAr": "سُورَةُ الرُّومِ",
    "nameFr": "Ar-Room",
    "ayat": 60,
    "parts": 5,
    "type": "مكية",
    "color": "#3b0764",
    "emoji": "🎯",
    "file": "surah-ar-rum.html",
    "available": true
  },
  {
    "id": "luqman",
    "num": 31,
    "nameAr": "سُورَةُ لُقۡمَانَ",
    "nameFr": "Luqman",
    "ayat": 34,
    "parts": 4,
    "type": "مكية",
    "color": "#334155",
    "emoji": "📖",
    "file": "surah-luqman.html",
    "available": true
  },
  {
    "id": "as-sajdah",
    "num": 32,
    "nameAr": "سُورَةُ السَّجۡدَةِ",
    "nameFr": "As-Sajda",
    "ayat": 30,
    "parts": 3,
    "type": "مكية",
    "color": "#4338ca",
    "emoji": "🎧",
    "file": "surah-as-sajdah.html",
    "available": true
  },
  {
    "id": "al-ahzab",
    "num": 33,
    "nameAr": "سُورَةُ الأَحۡزَابِ",
    "nameFr": "Al-Ahzaab",
    "ayat": 73,
    "parts": 5,
    "type": "مدنية",
    "color": "#be123c",
    "emoji": "🌙",
    "file": "surah-al-ahzab.html",
    "available": true
  },
  {
    "id": "saba",
    "num": 34,
    "nameAr": "سُورَةُ سَبَإٍ",
    "nameFr": "Saba",
    "ayat": 54,
    "parts": 5,
    "type": "مكية",
    "color": "#7c2d12",
    "emoji": "✨",
    "file": "surah-saba.html",
    "available": true
  },
  {
    "id": "fatir",
    "num": 35,
    "nameAr": "سُورَةُ فَاطِرٍ",
    "nameFr": "Faatir",
    "ayat": 45,
    "parts": 4,
    "type": "مكية",
    "color": "#0369a1",
    "emoji": "⚡",
    "file": "surah-fatir.html",
    "available": true
  },
  {
    "id": "ya-sin",
    "num": 36,
    "nameAr": "سُورَةُ يسٓ",
    "nameFr": "Yaseen",
    "ayat": 83,
    "parts": 6,
    "type": "مكية",
    "color": "#581c87",
    "emoji": "🌿",
    "file": "surah-ya-sin.html",
    "available": true
  },
  {
    "id": "as-saffat",
    "num": 37,
    "nameAr": "سُورَةُ الصَّافَّاتِ",
    "nameFr": "As-Saaffaat",
    "ayat": 182,
    "parts": 10,
    "type": "مكية",
    "color": "#1e3a8a",
    "emoji": "🕌",
    "file": "surah-as-saffat.html",
    "available": true
  },
  {
    "id": "sad",
    "num": 38,
    "nameAr": "سُورَةُ صٓ",
    "nameFr": "Saad",
    "ayat": 88,
    "parts": 6,
    "type": "مكية",
    "color": "#9a3412",
    "emoji": "🏆",
    "file": "surah-sad.html",
    "available": true
  },
  {
    "id": "az-zumar",
    "num": 39,
    "nameAr": "سُورَةُ الزُّمَرِ",
    "nameFr": "Az-Zumar",
    "ayat": 75,
    "parts": 5,
    "type": "مكية",
    "color": "#111827",
    "emoji": "💡",
    "file": "surah-az-zumar.html",
    "available": true
  },
  {
    "id": "ghafir",
    "num": 40,
    "nameAr": "سُورَةُ غَافِرٍ",
    "nameFr": "Ghafir",
    "ayat": 85,
    "parts": 6,
    "type": "مكية",
    "color": "#0f766e",
    "emoji": "🎯",
    "file": "surah-ghafir.html",
    "available": true
  },
  {
    "id": "fussilat",
    "num": 41,
    "nameAr": "سُورَةُ فُصِّلَتۡ",
    "nameFr": "Fussilat",
    "ayat": 54,
    "parts": 5,
    "type": "مكية",
    "color": "#0e7490",
    "emoji": "📖",
    "file": "surah-fussilat.html",
    "available": true
  },
  {
    "id": "ash-shura",
    "num": 42,
    "nameAr": "سُورَةُ الشُّورَىٰ",
    "nameFr": "Ash-Shura",
    "ayat": 53,
    "parts": 5,
    "type": "مكية",
    "color": "#92400e",
    "emoji": "🎧",
    "file": "surah-ash-shura.html",
    "available": true
  },
  {
    "id": "az-zukhruf",
    "num": 43,
    "nameAr": "سُورَةُ الزُّخۡرُفِ",
    "nameFr": "Az-Zukhruf",
    "ayat": 89,
    "parts": 6,
    "type": "مكية",
    "color": "#7f1d1d",
    "emoji": "🌙",
    "file": "surah-az-zukhruf.html",
    "available": true
  },
  {
    "id": "ad-dukhan",
    "num": 44,
    "nameAr": "سُورَةُ الدُّخَانِ",
    "nameFr": "Ad-Dukhaan",
    "ayat": 59,
    "parts": 5,
    "type": "مكية",
    "color": "#365314",
    "emoji": "✨",
    "file": "surah-ad-dukhan.html",
    "available": true
  },
  {
    "id": "al-jathiyah",
    "num": 45,
    "nameAr": "سُورَةُ الجَاثِيَةِ",
    "nameFr": "Al-Jaathiya",
    "ayat": 37,
    "parts": 4,
    "type": "مكية",
    "color": "#713f12",
    "emoji": "⚡",
    "file": "surah-al-jathiyah.html",
    "available": true
  },
  {
    "id": "al-ahqaf",
    "num": 46,
    "nameAr": "سُورَةُ الأَحۡقَافِ",
    "nameFr": "Al-Ahqaf",
    "ayat": 35,
    "parts": 4,
    "type": "مكية",
    "color": "#1d4ed8",
    "emoji": "🌿",
    "file": "surah-al-ahqaf.html",
    "available": true
  },
  {
    "id": "muhammad",
    "num": 47,
    "nameAr": "سُورَةُ مُحَمَّدٍ",
    "nameFr": "Muhammad",
    "ayat": 38,
    "parts": 4,
    "type": "مدنية",
    "color": "#854d0e",
    "emoji": "🕌",
    "file": "surah-muhammad.html",
    "available": true
  },
  {
    "id": "al-fath",
    "num": 48,
    "nameAr": "سُورَةُ الفَتۡحِ",
    "nameFr": "Al-Fath",
    "ayat": 29,
    "parts": 3,
    "type": "مدنية",
    "color": "#6d28d9",
    "emoji": "🏆",
    "file": "surah-al-fath.html",
    "available": true
  },
  {
    "id": "al-hujurat",
    "num": 49,
    "nameAr": "سُورَةُ الحُجُرَاتِ",
    "nameFr": "Al-Hujuraat",
    "ayat": 18,
    "parts": 3,
    "type": "مدنية",
    "color": "#1e40af",
    "emoji": "💡",
    "file": "surah-al-hujurat.html",
    "available": true
  },
  {
    "id": "qaf",
    "num": 50,
    "nameAr": "سُورَةُ قٓ",
    "nameFr": "Qaaf",
    "ayat": 45,
    "parts": 4,
    "type": "مكية",
    "color": "#0f172a",
    "emoji": "🎯",
    "file": "surah-qaf.html",
    "available": true
  },
  {
    "id": "adh-dhariyat",
    "num": 51,
    "nameAr": "سُورَةُ الذَّارِيَاتِ",
    "nameFr": "Adh-Dhaariyat",
    "ayat": 60,
    "parts": 5,
    "type": "مكية",
    "color": "#047857",
    "emoji": "📖",
    "file": "surah-adh-dhariyat.html",
    "available": true
  },
  {
    "id": "at-tur",
    "num": 52,
    "nameAr": "سُورَةُ الطُّورِ",
    "nameFr": "At-Tur",
    "ayat": 49,
    "parts": 4,
    "type": "مكية",
    "color": "#b45309",
    "emoji": "🎧",
    "file": "surah-at-tur.html",
    "available": true
  },
  {
    "id": "an-najm",
    "num": 53,
    "nameAr": "سُورَةُ النَّجۡمِ",
    "nameFr": "An-Najm",
    "ayat": 62,
    "parts": 5,
    "type": "مكية",
    "color": "#ea580c",
    "emoji": "🌙",
    "file": "surah-an-najm.html",
    "available": true
  },
  {
    "id": "al-qamar",
    "num": 54,
    "nameAr": "سُورَةُ القَمَرِ",
    "nameFr": "Al-Qamar",
    "ayat": 55,
    "parts": 5,
    "type": "مكية",
    "color": "#78350f",
    "emoji": "✨",
    "file": "surah-al-qamar.html",
    "available": true
  },
  {
    "id": "ar-rahman",
    "num": 55,
    "nameAr": "سُورَةُ الرَّحۡمَٰن",
    "nameFr": "Ar-Rahmaan",
    "ayat": 78,
    "parts": 5,
    "type": "مدنية",
    "color": "#ca8a04",
    "emoji": "⚡",
    "file": "surah-ar-rahman.html",
    "available": true
  },
  {
    "id": "al-waqiah",
    "num": 56,
    "nameAr": "سُورَةُ الوَاقِعَةِ",
    "nameFr": "Al-Waaqia",
    "ayat": 96,
    "parts": 6,
    "type": "مكية",
    "color": "#312e81",
    "emoji": "🌿",
    "file": "surah-al-waqiah.html",
    "available": true
  },
  {
    "id": "al-hadid",
    "num": 57,
    "nameAr": "سُورَةُ الحَدِيدِ",
    "nameFr": "Al-Hadid",
    "ayat": 29,
    "parts": 3,
    "type": "مدنية",
    "color": "#d97706",
    "emoji": "🕌",
    "file": "surah-al-hadid.html",
    "available": true
  },
  {
    "id": "al-mujadilah",
    "num": 58,
    "nameAr": "سُورَةُ المُجَادلَةِ",
    "nameFr": "Al-Mujaadila",
    "ayat": 22,
    "parts": 3,
    "type": "مدنية",
    "color": "#059669",
    "emoji": "🏆",
    "file": "surah-al-mujadilah.html",
    "available": true
  },
  {
    "id": "al-hashr",
    "num": 59,
    "nameAr": "سُورَةُ الحَشۡرِ",
    "nameFr": "Al-Hashr",
    "ayat": 24,
    "parts": 3,
    "type": "مدنية",
    "color": "#134e4a",
    "emoji": "💡",
    "file": "surah-al-hashr.html",
    "available": true
  },
  {
    "id": "al-mumtahanah",
    "num": 60,
    "nameAr": "سُورَةُ المُمۡتَحنَةِ",
    "nameFr": "Al-Mumtahana",
    "ayat": 13,
    "parts": 2,
    "type": "مدنية",
    "color": "#3b0764",
    "emoji": "🎯",
    "file": "surah-al-mumtahanah.html",
    "available": true
  },
  {
    "id": "as-saff",
    "num": 61,
    "nameAr": "سُورَةُ الصَّفِّ",
    "nameFr": "As-Saff",
    "ayat": 14,
    "parts": 2,
    "type": "مدنية",
    "color": "#334155",
    "emoji": "📖",
    "file": "surah-as-saff.html",
    "available": true
  },
  {
    "id": "al-jumuah",
    "num": 62,
    "nameAr": "سُورَةُ الجُمُعَةِ",
    "nameFr": "Al-Jumu'a",
    "ayat": 11,
    "parts": 2,
    "type": "مدنية",
    "color": "#4338ca",
    "emoji": "🎧",
    "file": "surah-al-jumuah.html",
    "available": true
  },
  {
    "id": "al-munafiqun",
    "num": 63,
    "nameAr": "سُورَةُ المُنَافِقُونَ",
    "nameFr": "Al-Munaafiqoon",
    "ayat": 11,
    "parts": 2,
    "type": "مدنية",
    "color": "#be123c",
    "emoji": "🌙",
    "file": "surah-al-munafiqun.html",
    "available": true
  },
  {
    "id": "at-taghabun",
    "num": 64,
    "nameAr": "سُورَةُ التَّغَابُنِ",
    "nameFr": "At-Taghaabun",
    "ayat": 18,
    "parts": 3,
    "type": "مدنية",
    "color": "#7c2d12",
    "emoji": "✨",
    "file": "surah-at-taghabun.html",
    "available": true
  },
  {
    "id": "at-talaq",
    "num": 65,
    "nameAr": "سُورَةُ الطَّلَاقِ",
    "nameFr": "At-Talaaq",
    "ayat": 12,
    "parts": 2,
    "type": "مدنية",
    "color": "#0369a1",
    "emoji": "⚡",
    "file": "surah-at-talaq.html",
    "available": true
  },
  {
    "id": "at-tahrim",
    "num": 66,
    "nameAr": "سُورَةُ التَّحۡرِيمِ",
    "nameFr": "At-Tahrim",
    "ayat": 12,
    "parts": 2,
    "type": "مدنية",
    "color": "#581c87",
    "emoji": "🌿",
    "file": "surah-at-tahrim.html",
    "available": true
  },
  {
    "id": "al-mulk",
    "num": 67,
    "nameAr": "سُورَةُ المُلۡكِ",
    "nameFr": "Al-Mulk",
    "ayat": 30,
    "parts": 3,
    "type": "مكية",
    "color": "#1e3a8a",
    "emoji": "🕌",
    "file": "surah-al-mulk.html",
    "available": true
  },
  {
    "id": "al-qalam",
    "num": 68,
    "nameAr": "سُورَةُ القَلَمِ",
    "nameFr": "Al-Qalam",
    "ayat": 52,
    "parts": 5,
    "type": "مكية",
    "color": "#9a3412",
    "emoji": "🏆",
    "file": "surah-al-qalam.html",
    "available": true
  },
  {
    "id": "al-haqqa",
    "num": 69,
    "nameAr": "سُورَةُ الحَاقَّةِ",
    "nameFr": "Al-Haaqqa",
    "ayat": 52,
    "parts": 5,
    "type": "مكية",
    "color": "#111827",
    "emoji": "💡",
    "file": "surah-al-haqqa.html",
    "available": true
  },
  {
    "id": "al-maarij",
    "num": 70,
    "nameAr": "سُورَةُ المَعَارِجِ",
    "nameFr": "Al-Ma'aarij",
    "ayat": 44,
    "parts": 4,
    "type": "مكية",
    "color": "#0f766e",
    "emoji": "🎯",
    "file": "surah-al-maarij.html",
    "available": true
  },
  {
    "id": "nuh",
    "num": 71,
    "nameAr": "سُورَةُ نُوحٍ",
    "nameFr": "Nooh",
    "ayat": 28,
    "parts": 3,
    "type": "مكية",
    "color": "#0e7490",
    "emoji": "📖",
    "file": "surah-nuh.html",
    "available": true
  },
  {
    "id": "al-jinn",
    "num": 72,
    "nameAr": "سُورَةُ الجِنِّ",
    "nameFr": "Al-Jinn",
    "ayat": 28,
    "parts": 3,
    "type": "مكية",
    "color": "#92400e",
    "emoji": "🎧",
    "file": "surah-al-jinn.html",
    "available": true
  },
  {
    "id": "al-muzzammil",
    "num": 73,
    "nameAr": "سُورَةُ المُزَّمِّلِ",
    "nameFr": "Al-Muzzammil",
    "ayat": 20,
    "parts": 3,
    "type": "مكية",
    "color": "#7f1d1d",
    "emoji": "🌙",
    "file": "surah-al-muzzammil.html",
    "available": true
  },
  {
    "id": "al-muddaththir",
    "num": 74,
    "nameAr": "سُورَةُ المُدَّثِّرِ",
    "nameFr": "Al-Muddaththir",
    "ayat": 56,
    "parts": 5,
    "type": "مكية",
    "color": "#365314",
    "emoji": "✨",
    "file": "surah-al-muddaththir.html",
    "available": true
  },
  {
    "id": "al-qiyama",
    "num": 75,
    "nameAr": "سُورَةُ القِيَامَةِ",
    "nameFr": "Al-Qiyaama",
    "ayat": 40,
    "parts": 4,
    "type": "مكية",
    "color": "#713f12",
    "emoji": "⚡",
    "file": "surah-al-qiyama.html",
    "available": true
  },
  {
    "id": "al-insan",
    "num": 76,
    "nameAr": "سُورَةُ الإِنسَانِ",
    "nameFr": "Al-Insaan",
    "ayat": 31,
    "parts": 4,
    "type": "مدنية",
    "color": "#1d4ed8",
    "emoji": "🌿",
    "file": "surah-al-insan.html",
    "available": true
  },
  {
    "id": "al-mursalat",
    "num": 77,
    "nameAr": "سُورَةُ المُرۡسَلَاتِ",
    "nameFr": "Al-Mursalaat",
    "ayat": 50,
    "parts": 4,
    "type": "مكية",
    "color": "#854d0e",
    "emoji": "🕌",
    "file": "surah-al-mursalat.html",
    "available": true
  },
  {
    "id": "an-naba",
    "num": 78,
    "nameAr": "سُورَةُ النَّبَإِ",
    "nameFr": "An-Naba",
    "ayat": 40,
    "parts": 4,
    "type": "مكية",
    "color": "#6d28d9",
    "emoji": "🏆",
    "file": "surah-an-naba.html",
    "available": true
  },
  {
    "id": "an-naziat",
    "num": 79,
    "nameAr": "سُورَةُ النَّازِعَاتِ",
    "nameFr": "An-Naazi'aat",
    "ayat": 46,
    "parts": 4,
    "type": "مكية",
    "color": "#1e40af",
    "emoji": "💡",
    "file": "surah-an-naziat.html",
    "available": true
  },
  {
    "id": "abasa",
    "num": 80,
    "nameAr": "سُورَةُ عَبَسَ",
    "nameFr": "Abasa",
    "ayat": 42,
    "parts": 4,
    "type": "مكية",
    "color": "#0f172a",
    "emoji": "🎯",
    "file": "surah-abasa.html",
    "available": true
  },
  {
    "id": "at-takwir",
    "num": 81,
    "nameAr": "سُورَةُ التَّكۡوِيرِ",
    "nameFr": "At-Takwir",
    "ayat": 29,
    "parts": 3,
    "type": "مكية",
    "color": "#047857",
    "emoji": "📖",
    "file": "surah-at-takwir.html",
    "available": true
  },
  {
    "id": "al-infitar",
    "num": 82,
    "nameAr": "سُورَةُ الانفِطَارِ",
    "nameFr": "Al-Infitaar",
    "ayat": 19,
    "parts": 3,
    "type": "مكية",
    "color": "#b45309",
    "emoji": "🎧",
    "file": "surah-al-infitar.html",
    "available": true
  },
  {
    "id": "al-mutaffifin",
    "num": 83,
    "nameAr": "سُورَةُ المُطَفِّفِينَ",
    "nameFr": "Al-Mutaffifin",
    "ayat": 36,
    "parts": 4,
    "type": "مكية",
    "color": "#ea580c",
    "emoji": "🌙",
    "file": "surah-al-mutaffifin.html",
    "available": true
  },
  {
    "id": "al-inshiqaq",
    "num": 84,
    "nameAr": "سُورَةُ الانشِقَاقِ",
    "nameFr": "Al-Inshiqaaq",
    "ayat": 25,
    "parts": 3,
    "type": "مكية",
    "color": "#78350f",
    "emoji": "✨",
    "file": "surah-al-inshiqaq.html",
    "available": true
  },
  {
    "id": "al-buruj",
    "num": 85,
    "nameAr": "سُورَةُ البُرُوجِ",
    "nameFr": "Al-Burooj",
    "ayat": 22,
    "parts": 3,
    "type": "مكية",
    "color": "#ca8a04",
    "emoji": "⚡",
    "file": "surah-al-buruj.html",
    "available": true
  },
  {
    "id": "at-tariq",
    "num": 86,
    "nameAr": "سُورَةُ الطَّارِقِ",
    "nameFr": "At-Taariq",
    "ayat": 17,
    "parts": 3,
    "type": "مكية",
    "color": "#312e81",
    "emoji": "🌿",
    "file": "surah-at-tariq.html",
    "available": true
  },
  {
    "id": "al-ala",
    "num": 87,
    "nameAr": "سُورَةُ الأَعۡلَىٰ",
    "nameFr": "Al-A'laa",
    "ayat": 19,
    "parts": 3,
    "type": "مكية",
    "color": "#d97706",
    "emoji": "🕌",
    "file": "surah-al-ala.html",
    "available": true
  },
  {
    "id": "al-ghashiya",
    "num": 88,
    "nameAr": "سُورَةُ الغَاشِيَةِ",
    "nameFr": "Al-Ghaashiya",
    "ayat": 26,
    "parts": 3,
    "type": "مكية",
    "color": "#059669",
    "emoji": "🏆",
    "file": "surah-al-ghashiya.html",
    "available": true
  },
  {
    "id": "al-fajr",
    "num": 89,
    "nameAr": "سُورَةُ الفَجۡرِ",
    "nameFr": "Al-Fajr",
    "ayat": 30,
    "parts": 3,
    "type": "مكية",
    "color": "#134e4a",
    "emoji": "💡",
    "file": "surah-al-fajr.html",
    "available": true
  },
  {
    "id": "al-balad",
    "num": 90,
    "nameAr": "سُورَةُ البَلَدِ",
    "nameFr": "Al-Balad",
    "ayat": 20,
    "parts": 3,
    "type": "مكية",
    "color": "#3b0764",
    "emoji": "🎯",
    "file": "surah-al-balad.html",
    "available": true
  },
  {
    "id": "ash-shams",
    "num": 91,
    "nameAr": "سُورَةُ الشَّمۡسِ",
    "nameFr": "Ash-Shams",
    "ayat": 15,
    "parts": 2,
    "type": "مكية",
    "color": "#334155",
    "emoji": "📖",
    "file": "surah-ash-shams.html",
    "available": true
  },
  {
    "id": "al-layl",
    "num": 92,
    "nameAr": "سُورَةُ اللَّيۡلِ",
    "nameFr": "Al-Lail",
    "ayat": 21,
    "parts": 3,
    "type": "مكية",
    "color": "#4338ca",
    "emoji": "🎧",
    "file": "surah-al-layl.html",
    "available": true
  },
  {
    "id": "ad-duha",
    "num": 93,
    "nameAr": "سُورَةُ الضُّحَىٰ",
    "nameFr": "Ad-Dhuhaa",
    "ayat": 11,
    "parts": 2,
    "type": "مكية",
    "color": "#be123c",
    "emoji": "🌙",
    "file": "surah-ad-duha.html",
    "available": true
  },
  {
    "id": "ash-sharh",
    "num": 94,
    "nameAr": "سُورَةُ الشَّرۡحِ",
    "nameFr": "Ash-Sharh",
    "ayat": 8,
    "parts": 2,
    "type": "مكية",
    "color": "#7c2d12",
    "emoji": "✨",
    "file": "surah-ash-sharh.html",
    "available": true
  },
  {
    "id": "al-tin",
    "num": 95,
    "nameAr": "سُورَةُ التِّينِ",
    "nameFr": "At-Tin",
    "ayat": 8,
    "parts": 2,
    "type": "مكية",
    "color": "#0369a1",
    "emoji": "⚡",
    "file": "Al_Tin.html",
    "available": true
  },
  {
    "id": "al-alaq",
    "num": 96,
    "nameAr": "سُورَةُ العَلَقِ",
    "nameFr": "Al-Alaq",
    "ayat": 19,
    "parts": 3,
    "type": "مكية",
    "color": "#581c87",
    "emoji": "🌿",
    "file": "Al_Alaq.html",
    "available": true
  },
  {
    "id": "al-qadr",
    "num": 97,
    "nameAr": "سُورَةُ القَدۡرِ",
    "nameFr": "Al-Qadr",
    "ayat": 5,
    "parts": 1,
    "type": "مكية",
    "color": "#1e3a8a",
    "emoji": "🕌",
    "file": "al_kadr.html",
    "available": true
  },
  {
    "id": "al-bayyina",
    "num": 98,
    "nameAr": "سُورَةُ البَيِّنَةِ",
    "nameFr": "Al-Bayyina",
    "ayat": 8,
    "parts": 2,
    "type": "مدنية",
    "color": "#9a3412",
    "emoji": "🏆",
    "file": "bayina.html",
    "available": true
  },
  {
    "id": "al-zalzala",
    "num": 99,
    "nameAr": "سُورَةُ الزَّلۡزَلَةِ",
    "nameFr": "Az-Zalzala",
    "ayat": 8,
    "parts": 2,
    "type": "مدنية",
    "color": "#111827",
    "emoji": "💡",
    "file": "surah-zalzalah.html",
    "available": true
  },
  {
    "id": "al-adiyat",
    "num": 100,
    "nameAr": "سُورَةُ العَادِيَاتِ",
    "nameFr": "Al-Aadiyaat",
    "ayat": 11,
    "parts": 2,
    "type": "مكية",
    "color": "#0f766e",
    "emoji": "🎯",
    "file": "surah-adiyat.html",
    "available": true
  },
  {
    "id": "al-qaria",
    "num": 101,
    "nameAr": "سُورَةُ القَارِعَةِ",
    "nameFr": "Al-Qaari'a",
    "ayat": 11,
    "parts": 2,
    "type": "مكية",
    "color": "#0e7490",
    "emoji": "📖",
    "file": "qaria.html",
    "available": true
  },
  {
    "id": "al-takathur",
    "num": 102,
    "nameAr": "سُورَةُ التَّكَاثُرِ",
    "nameFr": "At-Takaathur",
    "ayat": 8,
    "parts": 2,
    "type": "مكية",
    "color": "#92400e",
    "emoji": "🎧",
    "file": "surah-takathur.html",
    "available": true
  },
  {
    "id": "al-asr",
    "num": 103,
    "nameAr": "سُورَةُ العَصۡرِ",
    "nameFr": "Al-Asr",
    "ayat": 3,
    "parts": 1,
    "type": "مكية",
    "color": "#7f1d1d",
    "emoji": "🌙",
    "file": "surah-asr.html",
    "available": true
  },
  {
    "id": "al-humaza",
    "num": 104,
    "nameAr": "سُورَةُ الهُمَزَةِ",
    "nameFr": "Al-Humaza",
    "ayat": 9,
    "parts": 2,
    "type": "مكية",
    "color": "#365314",
    "emoji": "✨",
    "file": "surah-humaza.html",
    "available": true
  },
  {
    "id": "al-fil",
    "num": 105,
    "nameAr": "سُورَةُ الفِيلِ",
    "nameFr": "Al-Fil",
    "ayat": 5,
    "parts": 1,
    "type": "مكية",
    "color": "#713f12",
    "emoji": "⚡",
    "file": "fil.html",
    "available": true
  },
  {
    "id": "quraysh",
    "num": 106,
    "nameAr": "سُورَةُ قُرَيۡشٍ",
    "nameFr": "Quraish",
    "ayat": 4,
    "parts": 1,
    "type": "مكية",
    "color": "#1d4ed8",
    "emoji": "🌿",
    "file": "quraysh.html",
    "available": true
  },
  {
    "id": "al-maun",
    "num": 107,
    "nameAr": "سُورَةُ المَاعُونِ",
    "nameFr": "Al-Maa'un",
    "ayat": 7,
    "parts": 1,
    "type": "مكية",
    "color": "#854d0e",
    "emoji": "🕌",
    "file": "surah-al-maun.html",
    "available": true
  },
  {
    "id": "al-kawthar",
    "num": 108,
    "nameAr": "سُورَةُ الكَوۡثَرِ",
    "nameFr": "Al-Kawthar",
    "ayat": 3,
    "parts": 1,
    "type": "مكية",
    "color": "#6d28d9",
    "emoji": "🏆",
    "file": "surah-al-kawthar.html",
    "available": true
  },
  {
    "id": "al-kafirun",
    "num": 109,
    "nameAr": "سُورَةُ الكَافِرُونَ",
    "nameFr": "Al-Kaafiroon",
    "ayat": 6,
    "parts": 1,
    "type": "مكية",
    "color": "#1e40af",
    "emoji": "💡",
    "file": "surah-al-kafirun.html",
    "available": true
  },
  {
    "id": "al-nasr",
    "num": 110,
    "nameAr": "سُورَةُ النَّصۡرِ",
    "nameFr": "An-Nasr",
    "ayat": 3,
    "parts": 1,
    "type": "مدنية",
    "color": "#0f172a",
    "emoji": "🎯",
    "file": "surah-al-nasr.html",
    "available": true
  },
  {
    "id": "al-masad",
    "num": 111,
    "nameAr": "سُورَةُ المَسَدِ",
    "nameFr": "Al-Masad",
    "ayat": 5,
    "parts": 1,
    "type": "مكية",
    "color": "#047857",
    "emoji": "📖",
    "file": "surah-al-masad.html",
    "available": true
  },
  {
    "id": "al-ikhlas",
    "num": 112,
    "nameAr": "سُورَةُ الإِخۡلَاصِ",
    "nameFr": "Al-Ikhlaas",
    "ayat": 4,
    "parts": 1,
    "type": "مكية",
    "color": "#b45309",
    "emoji": "🎧",
    "file": "surah-al-ikhlas.html",
    "available": true
  },
  {
    "id": "al-falaq",
    "num": 113,
    "nameAr": "سُورَةُ الفَلَقِ",
    "nameFr": "Al-Falaq",
    "ayat": 5,
    "parts": 1,
    "type": "مكية",
    "color": "#ea580c",
    "emoji": "🌙",
    "file": "surah-al-falaq.html",
    "available": true
  },
  {
    "id": "al-nas",
    "num": 114,
    "nameAr": "سُورَةُ النَّاسِ",
    "nameFr": "An-Naas",
    "ayat": 6,
    "parts": 1,
    "type": "مكية",
    "color": "#78350f",
    "emoji": "✨",
    "file": "surah-al-nas.html",
    "available": true
  }
];
