"use client";

import { Archive, Bell, BellRing, CheckCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Button, Drawer, IconButton, useToast } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import type { DatabaseNotificationCategory, DatabaseNotificationPriority } from "@/types/database";
import { enablePushNotifications } from "./push-subscription";

type NotificationItem = { id: string; title: string; body: string; href: string | null; read_at: string | null; archived_at: string | null; created_at: string; category: DatabaseNotificationCategory; priority: DatabaseNotificationPriority };
type Filter = "all" | "unread" | DatabaseNotificationCategory;
const labels: Record<DatabaseNotificationCategory, string> = { message: "الرسائل", request: "الطلبات", assignment: "الواجبات", learning: "التعلّم", attendance: "الحضور", session: "الحصص", administration: "الإدارة", system: "النظام" };

export function NotificationCenter() {
  const { showToast } = useToast(); const [open, setOpen] = useState(false); const [filter, setFilter] = useState<Filter>("all"); const [items, setItems] = useState<NotificationItem[]>([]);
  useEffect(() => { const client = createClient(); let userId: string | undefined; void client.auth.getUser().then(async ({ data }) => { userId = data.user?.id; if (!userId) return; const result = await client.from("user_notifications").select("id,title,body,href,read_at,archived_at,created_at,category,priority").eq("user_id", userId).is("archived_at", null).order("created_at", { ascending: false }).limit(100); setItems(result.data ?? []); }); const channel = client.channel(`notifications:${crypto.randomUUID()}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "user_notifications" }, (payload) => { const item = payload.new as NotificationItem & { user_id?: string }; if (userId && item.user_id !== userId) return; setItems((current) => [item, ...current].slice(0, 100)); showToast({ title: item.title, description: item.body, tone: "info" }); if (Notification.permission === "granted") void navigator.serviceWorker?.ready.then((registration) => registration.showNotification(item.title, { body: item.body, tag: item.id, data: { href: item.href } })); }).subscribe(); return () => { void client.removeChannel(channel); }; }, [showToast]);
  const unread = items.filter((item) => !item.read_at).length; const visible = useMemo(() => items.filter((item) => filter === "all" || filter === "unread" ? filter === "all" || !item.read_at : item.category === filter), [filter, items]);
  async function markRead(item: NotificationItem) { if (!item.read_at) await createClient().rpc("mark_notification_read", { target_notification_id: item.id }); setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, read_at: entry.read_at ?? new Date().toISOString() } : entry)); if (item.href) window.location.assign(item.href); }
  async function markAll() { await createClient().rpc("mark_all_notifications_read"); setItems((current) => current.map((item) => ({ ...item, read_at: item.read_at ?? new Date().toISOString() }))); }
  async function archive(id: string) { await createClient().rpc("archive_notification", { target_notification_id: id, target_archived: true }); setItems((current) => current.filter((item) => item.id !== id)); }
  async function enableBrowser() { try { await enablePushNotifications(); await createClient().rpc("set_notification_channels", { target_category: "system", target_in_app: true, target_push: true, target_email: false, target_sms: false, target_whatsapp: false, target_digest_frequency: "immediate", target_quiet_start: null, target_quiet_end: null }); showToast({ title: "تم تفعيل إشعارات الجهاز", tone: "success" }); } catch (error) { showToast({ title: error instanceof Error ? error.message : "تعذر تفعيل الإشعارات", tone: "info" }); } }
  return <><span className="notification-trigger"><IconButton label="الإشعارات" onClick={() => setOpen(true)}>{unread ? <BellRing aria-hidden="true" size={20} /> : <Bell aria-hidden="true" size={20} />}</IconButton>{unread ? <b>{Math.min(unread, 99)}</b> : null}</span><Drawer open={open} onOpenChange={setOpen} title="الإشعارات"><div className="notification-actions"><Button variant="secondary" size="sm" onClick={() => void enableBrowser()}><Bell size={17} />تفعيل الجهاز</Button><Button variant="quiet" size="sm" onClick={() => void markAll()}><CheckCheck size={17} />قراءة الكل</Button></div><div className="notification-filters"><button className={filter === "all" ? "is-active" : undefined} onClick={() => setFilter("all")}>الكل</button><button className={filter === "unread" ? "is-active" : undefined} onClick={() => setFilter("unread")}>غير المقروء</button>{(["message","assignment","attendance","administration"] as DatabaseNotificationCategory[]).map((category) => <button key={category} className={filter === category ? "is-active" : undefined} onClick={() => setFilter(category)}>{labels[category]}</button>)}</div><div className="notification-list">{visible.length ? visible.map((item) => <article className={item.read_at ? undefined : "is-unread"} key={item.id}><button type="button" onClick={() => void markRead(item)}><span><strong>{item.title}</strong><small>{item.body}</small><time>{new Intl.DateTimeFormat("ar-MA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.created_at))}</time></span>{item.read_at ? <CheckCheck size={16} /> : <i />}</button><IconButton label="أرشفة" onClick={() => void archive(item.id)}><Archive size={16} /></IconButton></article>) : <p className="notification-empty">لا توجد إشعارات في هذا القسم.</p>}</div></Drawer></>;
}
