"use client";

import { useState } from "react";
import { CalendarDays, FileText, HandCoins, Send, ShieldAlert } from "lucide-react";
import { Badge, Button, EmptyState, useToast } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import type { DatabaseTeacherRequestKind } from "@/types/database";
import type { TeacherProfessionalData } from "./models";

type Tab = "planning" | "requests" | "salary" | "documents" | "reports";
const labels: Record<Tab, string> = { planning: "التخطيط", requests: "الطلبات", salary: "الراتب", documents: "الوثائق", reports: "التقارير" };

export function ProfessionalWorkspace({ data, initialTab = "planning" }: { data: TeacherProfessionalData; initialTab?: Tab }) {
  const [tab, setTab] = useState<Tab>(initialTab);
  return <div className="teacher-workspace"><header className="teacher-hero"><div><span>المساحة المهنية</span><h1>كل شؤونك المهنية في مكان واضح</h1><p>تابع جدولك وطلباتك وراتبك ووثائقك وتقارير حصصك.</p></div></header><nav className="teacher-tabs" aria-label="أقسام المساحة المهنية">{(Object.keys(labels) as Tab[]).map((item) => <button type="button" className={tab === item ? "is-active" : undefined} aria-current={tab === item ? "page" : undefined} key={item} onClick={() => setTab(item)}>{labels[item]}</button>)}</nav>{tab === "planning" ? <Planning data={data} /> : null}{tab === "requests" ? <Requests data={data} /> : null}{tab === "salary" ? <Salary data={data} onProblem={() => setTab("requests")} /> : null}{tab === "documents" ? <Documents data={data} /> : null}{tab === "reports" ? <Reports data={data} /> : null}</div>;
}

function Planning({ data }: { data: TeacherProfessionalData }) { return <section className="professional-panel"><header><h1>الجدول</h1><p>الحصص المقبلة والسابقة المسجلة في المؤسسة.</p></header>{data.schedule.length ? <div className="teacher-record-list">{data.schedule.map((item) => <article key={item.id}><div><strong>{item.title} · {item.className}</strong><small>{formatDate(item.startsAt)} · {item.location ?? "المكان غير محدد"}</small></div><Badge tone={item.status === "completed" ? "success" : "brand"}>{item.status === "completed" ? "منجزة" : "مجدولة"}</Badge></article>)}</div> : <EmptyState title="لا توجد حصص" description="سيظهر جدول المؤسسة هنا فور إضافته." icon={CalendarDays} />}</section>; }

function Requests({ data }: { data: TeacherProfessionalData }) {
  const { showToast } = useToast();
  const [kind, setKind] = useState<DatabaseTeacherRequestKind>("general"); const [title, setTitle] = useState(""); const [details, setDetails] = useState(""); const [startsOn, setStartsOn] = useState(""); const [endsOn, setEndsOn] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(): Promise<void> { if (title.trim().length < 3) return; setBusy(true); const { error } = await createClient().rpc("teacher_create_request", { target_kind: kind, target_title: title, target_details: details, target_starts_on: startsOn || null, target_ends_on: endsOn || null }); setBusy(false); if (error) { showToast({ title: "تعذر إرسال الطلب", tone: "info" }); return; } showToast({ title: "تم إرسال الطلب إلى الإدارة", tone: "success" }); setTitle(""); setDetails(""); setStartsOn(""); setEndsOn(""); window.location.reload(); }
  async function cancel(id: string): Promise<void> { setBusy(true); const { error } = await createClient().rpc("teacher_cancel_request", { target_request_id: id }); setBusy(false); if (error) { showToast({ title: "تعذر إلغاء الطلب", tone: "info" }); return; } showToast({ title: "تم إلغاء الطلب", tone: "success" }); window.location.reload(); }
  return <section className="professional-panel" id="requests"><header><h1>طلب جديد</h1><p>الغياب والإجازة والراتب والمعدات والجدول عبر مسار واحد واضح.</p></header><div className="teacher-form"><label>نوع الطلب<select value={kind} onChange={(event) => setKind(event.target.value as DatabaseTeacherRequestKind)}><option value="general">طلب عام</option><option value="absence">إشعار غياب</option><option value="leave">طلب إجازة</option><option value="salary_problem">مشكلة في الراتب</option><option value="equipment">طلب معدات</option><option value="schedule">مشكلة في الجدول</option></select></label><label>العنوان<input value={title} maxLength={100} onChange={(event) => setTitle(event.target.value)} /></label><label>التفاصيل<textarea value={details} maxLength={1000} onChange={(event) => setDetails(event.target.value)} /></label>{kind === "absence" || kind === "leave" ? <div className="form-pair"><label>من<input type="date" value={startsOn} onChange={(event) => setStartsOn(event.target.value)} /></label><label>إلى<input type="date" value={endsOn} onChange={(event) => setEndsOn(event.target.value)} /></label></div> : null}<Button loading={busy} disabled={title.trim().length < 3} onClick={() => void submit()}><Send size={18} />إرسال إلى الإدارة</Button></div><header><h2>متابعة الطلبات</h2></header>{data.requests.length ? <div className="teacher-record-list">{data.requests.map((item) => <article key={item.id}><div><strong>{item.title}</strong><small>{requestKind(item.kind)} · {formatDate(item.submittedAt)}{item.adminResponse ? ` · رد الإدارة: ${item.adminResponse}` : ""}</small>{item.status === "submitted" ? <button className="teacher-inline-action" type="button" disabled={busy} onClick={() => void cancel(item.id)}>إلغاء الطلب</button> : null}</div><Badge tone={requestTone(item.status)}>{requestStatus(item.status)}</Badge></article>)}</div> : <EmptyState title="لا توجد طلبات" description="الطلبات المرسلة ستظهر هنا مع حالتها." />}</section>;
}

function Salary({ data, onProblem }: { data: TeacherProfessionalData; onProblem: () => void }) { return <section className="professional-panel"><header><h1>الراتب</h1><p>كشف واضح لكل شهر وحالة الصرف.</p></header>{data.salaries.length ? <div className="teacher-record-list">{data.salaries.map((item) => <article key={item.id}><div><strong>{formatMonth(item.month)} · {item.net.toFixed(2)} {item.currency}</strong><small>الإجمالي {item.gross.toFixed(2)} · الاقتطاعات {item.deductions.toFixed(2)}</small></div><Badge tone={item.status === "paid" ? "success" : item.status === "issue_reported" ? "danger" : "warning"}>{salaryStatus(item.status)}</Badge></article>)}</div> : <EmptyState title="لا توجد كشوف راتب" description="ستظهر الكشوف فور نشرها من الإدارة." icon={HandCoins} />}<Button variant="secondary" onClick={onProblem}><ShieldAlert size={18} />الإبلاغ عن مشكلة راتب</Button></section>; }
function Documents({ data }: { data: TeacherProfessionalData }) { return <section className="professional-panel"><header><h1>الوثائق</h1><p>الوثائق التي أتاحت لك الإدارة.</p></header>{data.documents.length ? <div className="teacher-record-list">{data.documents.map((item) => <article key={item.id}><div><strong>{item.title}</strong><small>{item.category} · {formatDate(item.visibleFrom)}</small></div><a className="ui-button ui-button--secondary ui-button--sm" href={item.storagePath} target="_blank" rel="noreferrer">فتح</a></article>)}</div> : <EmptyState title="لا توجد وثائق" description="ستظهر العقود والكشوف والوثائق المصرح بها هنا." icon={FileText} />}</section>; }
function Reports({ data }: { data: TeacherProfessionalData }) { return <section className="professional-panel"><header><h1>تقارير الحصص</h1><p>أرشيف التقارير المرسلة إلى الإدارة.</p></header>{data.reports.length ? <div className="teacher-record-list">{data.reports.map((item) => <article key={item.id}><div><strong>تقرير الحصة</strong><small>{item.submittedAt ? formatDate(item.submittedAt) : "مسودة"} · حاضر {item.present} · غائب {item.absent} · متأخر {item.late}</small></div><Badge tone={item.status === "submitted" || item.status === "seen" || item.status === "resolved" ? "success" : "warning"}>{requestStatus(item.status)}</Badge></article>)}</div> : <EmptyState title="لا توجد تقارير" description="بعد إنهاء أول حصة سيظهر التقرير هنا." />}</section>; }

function requestStatus(value: string): string { return ({ submitted: "مرسل", seen: "تم الاطلاع", in_review: "قيد المراجعة", approved: "مقبول", rejected: "مرفوض", resolved: "تمت المعالجة", cancelled: "ملغى", draft: "مسودة" } as Record<string, string>)[value] ?? value; }
function requestKind(value: string): string { return ({ absence: "غياب", leave: "إجازة", salary_problem: "راتب", equipment: "معدات", schedule: "جدول", general: "عام" } as Record<string, string>)[value] ?? value; }
function requestTone(value: string): "neutral" | "success" | "warning" | "danger" | "brand" { if (["approved", "resolved"].includes(value)) return "success"; if (value === "rejected") return "danger"; if (["seen", "in_review"].includes(value)) return "brand"; return "warning"; }
function salaryStatus(value: string): string { return ({ pending: "في الانتظار", paid: "تم الصرف", issue_reported: "تم الإبلاغ", resolved: "تمت المعالجة" } as Record<string, string>)[value] ?? value; }
function formatDate(value: string): string { return new Intl.DateTimeFormat("ar-MA", { dateStyle: "medium", timeStyle: value.includes("T") ? "short" : undefined }).format(new Date(value)); }
function formatMonth(value: string): string { return new Intl.DateTimeFormat("ar-MA", { month: "long", year: "numeric" }).format(new Date(value)); }
