"use client";

import { CalendarDays, FileText, Send, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { Badge, Button, EmptyState, useToast } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import type { DatabaseTeacherRequestKind } from "@/types/database";
import type { TeacherProfessionalData } from "./models";

type Tab = "planning" | "requests" | "salary" | "documents" | "reports";
const labels: Record<Tab, string> = { planning: "الجدول", requests: "الطلبات", salary: "الراتب", documents: "الوثائق", reports: "تقاريري" };

export function ProfessionalWorkspace({ data, initialTab = "planning" }: { data: TeacherProfessionalData; initialTab?: Tab }) {
  const [tab, setTab] = useState<Tab>(initialTab);
  return <div className="teacher-workspace"><header className="teacher-page-head"><span>الملف المهني</span><h1>{data.teacher?.name ?? "ملفي"}</h1></header><nav className="teacher-tabs" aria-label="أقسام الملف المهني">{(Object.keys(labels) as Tab[]).map((item) => <button type="button" className={tab === item ? "is-active" : undefined} aria-current={tab === item ? "page" : undefined} key={item} onClick={() => setTab(item)}>{labels[item]}</button>)}</nav>{tab === "planning" ? <Planning data={data} /> : null}{tab === "requests" ? <Requests data={data} /> : null}{tab === "salary" ? <Salary data={data} onProblem={() => setTab("requests")} /> : null}{tab === "documents" ? <Documents data={data} /> : null}{tab === "reports" ? <Reports data={data} /> : null}</div>;
}

function Planning({ data }: { data: TeacherProfessionalData }) { return <section className="professional-panel"><h2>الجدول</h2>{data.schedule.length ? <div className="teacher-record-list">{data.schedule.map((item) => <article key={item.id}><div><strong>{item.title} · {item.className}</strong><small>{formatDate(item.startsAt)} · {item.location ?? "المكان غير محدد"}</small></div><Badge tone={item.status === "completed" ? "success" : "brand"}>{item.status === "completed" ? "منجزة" : "مجدولة"}</Badge></article>)}</div> : <EmptyState title="لا توجد حصص" description="سيظهر جدول المؤسسة هنا." icon={CalendarDays} />}</section>; }

function Requests({ data }: { data: TeacherProfessionalData }) {
  const { showToast } = useToast(); const [kind, setKind] = useState<DatabaseTeacherRequestKind>("general"); const [title, setTitle] = useState(""); const [details, setDetails] = useState(""); const [startsOn, setStartsOn] = useState(""); const [endsOn, setEndsOn] = useState(""); const [busy, setBusy] = useState(false);
  async function submit() { if (title.trim().length < 3) return; setBusy(true); const result = await createClient().rpc("teacher_create_request", { target_kind: kind, target_title: title, target_details: details, target_starts_on: startsOn || null, target_ends_on: endsOn || null }); setBusy(false); if (result.error) return showToast({ title: "تعذر إرسال الطلب", tone: "info" }); showToast({ title: "تم إرسال الطلب إلى الإدارة", tone: "success" }); window.location.reload(); }
  async function cancel(id: string) { setBusy(true); const result = await createClient().rpc("teacher_cancel_request", { target_request_id: id }); setBusy(false); if (result.error) return showToast({ title: "تعذر إلغاء الطلب", tone: "info" }); window.location.reload(); }
  const dated = kind === "absence" || kind === "late" || kind === "leave";
  return <section className="professional-panel" id="requests"><h2>طلب جديد</h2><div className="teacher-form"><label>النوع<select value={kind} onChange={(event) => setKind(event.target.value as DatabaseTeacherRequestKind)}><option value="absence">إشعار غياب</option><option value="late">إشعار تأخر</option><option value="leave">طلب إجازة</option><option value="salary_problem">مشكلة راتب</option><option value="equipment">طلب معدات</option><option value="schedule">مشكلة في الجدول</option><option value="general">طلب عام</option></select></label><label>العنوان<input value={title} maxLength={100} onChange={(event) => setTitle(event.target.value)} /></label><label>التفاصيل<textarea value={details} maxLength={1000} onChange={(event) => setDetails(event.target.value)} /></label>{dated ? <div className="form-pair"><label>من<input type="date" value={startsOn} onChange={(event) => setStartsOn(event.target.value)} /></label><label>إلى<input type="date" value={endsOn} onChange={(event) => setEndsOn(event.target.value)} /></label></div> : null}<Button loading={busy} disabled={title.trim().length < 3} onClick={() => void submit()}><Send size={18} />إرسال إلى الإدارة</Button></div><h2>سجل الطلبات</h2>{data.requests.length ? <div className="teacher-record-list">{data.requests.map((item) => <article key={item.id}><div><strong>{item.title}</strong><small>{requestKind(item.kind)} · {formatDate(item.submittedAt)}</small>{item.adminResponse ? <p>رد الإدارة: {item.adminResponse}</p> : null}{item.status === "submitted" ? <button className="teacher-inline-action" type="button" disabled={busy} onClick={() => void cancel(item.id)}>إلغاء الطلب</button> : null}</div><Badge tone={requestTone(item.status)}>{requestStatus(item.status)}</Badge></article>)}</div> : <EmptyState title="لا توجد طلبات" description="الطلبات المرسلة ستظهر هنا." />}</section>;
}

function Salary({ data, onProblem }: { data: TeacherProfessionalData; onProblem: () => void }) {
  const year = new Date().getFullYear(); const byMonth = new Map(data.salaries.map((item) => [new Date(item.month).getMonth(), item]));
  return <section className="professional-panel"><h2>الراتب</h2><div className="salary-calendar">{Array.from({ length: 12 }, (_, month) => { const item = byMonth.get(month); return <details key={month}><summary><span>{monthName(month, year)}</span><Badge tone={item?.status === "paid" ? "success" : item ? "warning" : "neutral"}>{item ? salaryStatus(item.status) : "غير مسجل"}</Badge></summary>{item ? <div><strong>{item.net.toFixed(2)} {item.currency}</strong><small>الإجمالي {item.gross.toFixed(2)} · الاقتطاعات {item.deductions.toFixed(2)}</small>{item.paidAt ? <small>تاريخ الصرف: {formatDate(item.paidAt)}</small> : null}</div> : <p>لا توجد بيانات لهذا الشهر.</p>}</details>; })}</div><Button variant="secondary" onClick={onProblem}><ShieldAlert size={18} />الإبلاغ عن مشكلة راتب</Button></section>;
}

function Documents({ data }: { data: TeacherProfessionalData }) { return <section className="professional-panel"><h2>الوثائق</h2>{data.documents.length ? <div className="teacher-record-list">{data.documents.map((item) => <article key={item.id}><div><strong>{item.title}</strong><small>{item.category} · {formatDate(item.visibleFrom)}</small></div><a className="ui-button ui-button--secondary ui-button--sm" href={item.storagePath} target="_blank" rel="noreferrer">فتح</a></article>)}</div> : <EmptyState title="لا توجد وثائق" description="ستظهر الوثائق المصرح بها هنا." icon={FileText} />}</section>; }
function Reports({ data }: { data: TeacherProfessionalData }) { return <section className="professional-panel"><h2>تقارير الحصص</h2>{data.reports.length ? <div className="teacher-record-list">{data.reports.map((item) => <details className="teacher-report-row" key={item.id}><summary><span>تقرير الحصة · {item.submittedAt ? formatDate(item.submittedAt) : "مسودة"}</span><Badge tone={item.status === "submitted" || item.status === "seen" || item.status === "resolved" ? "success" : "warning"}>{requestStatus(item.status)}</Badge></summary><div><span>حاضر {item.present}</span><span>غائب {item.absent}</span><span>متأخر {item.late}</span></div></details>)}</div> : <EmptyState title="لا توجد تقارير" description="بعد إنهاء أول حصة سيظهر التقرير هنا." />}</section>; }

function requestStatus(value: string) { return ({ submitted: "مرسل", seen: "تم الاطلاع", in_review: "قيد المراجعة", approved: "مقبول", rejected: "مرفوض", resolved: "تمت المعالجة", cancelled: "ملغى", draft: "مسودة" } as Record<string, string>)[value] ?? value; }
function requestKind(value: string) { return ({ absence: "غياب", late: "تأخر", leave: "إجازة", salary_problem: "راتب", equipment: "معدات", schedule: "جدول", general: "عام" } as Record<string, string>)[value] ?? value; }
function requestTone(value: string): "neutral" | "success" | "warning" | "danger" | "brand" { if (["approved", "resolved"].includes(value)) return "success"; if (value === "rejected") return "danger"; if (["seen", "in_review"].includes(value)) return "brand"; return "warning"; }
function salaryStatus(value: string) { return ({ pending: "في الانتظار", paid: "تم الصرف", issue_reported: "مشكلة مسجلة", resolved: "تمت المعالجة" } as Record<string, string>)[value] ?? value; }
function formatDate(value: string) { return new Intl.DateTimeFormat("ar-MA", { dateStyle: "medium", timeStyle: value.includes("T") ? "short" : undefined }).format(new Date(value)); }
function monthName(month: number, year: number) { return new Intl.DateTimeFormat("ar-MA", { month: "long", year: "numeric" }).format(new Date(year, month, 1)); }
