"use client";

import { AlertTriangle, ArrowLeft, ArrowRight, Check, Clock3, Flag, Play, Send, StopCircle } from "lucide-react";
import { useEffect, useState } from "react";
import type { Dispatch, SetStateAction } from "react";
import { useRouter } from "next/navigation";
import { Badge, Button, useToast } from "@/components/ui";
import { getAllSurahs, getSurah } from "@/features/quran/canonical";
import { createClient } from "@/lib/supabase/client";
import type { DatabaseAttendanceStatus, DatabaseRecitationAppreciation } from "@/types/database";
import type { TeacherSessionData } from "./models";

type AttendanceState = Record<string, { status: DatabaseAttendanceStatus; minutesLate: number }>;
const difficulties = ["ضعف التركيز", "نسيان متكرر", "صعوبة الربط", "قلة المراجعة"];

export function SessionWizard({ data }: { data: TeacherSessionData }) {
  const router = useRouter(); const { showToast } = useToast();
  const [runId, setRunId] = useState(data.openRun?.id ?? null); const [reportId, setReportId] = useState(data.openReportId);
  const [step, setStep] = useState(data.openRun?.status === "report_pending" ? 3 : data.openRun ? 1 : 0);
  const [startedAt, setStartedAt] = useState(data.openRun?.startedAt ?? null); const [seconds, setSeconds] = useState(data.elapsedSeconds);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [worked, setWorked] = useState(() => new Set(data.attendance.filter(({ processed }) => processed).map(({ studentId }) => studentId)));
  const initialAttendance = Object.fromEntries(data.students.map((student) => { const stored = data.attendance.find((item) => item.studentId === student.id); return [student.id, { status: stored?.status ?? "absent", minutesLate: stored?.minutesLate ?? 0 }]; }));
  const [attendance, setAttendance] = useState<AttendanceState>(initialAttendance);
  const [selectedClassId, setSelectedClassId] = useState(data.openRun?.classId ?? data.nextCourse?.classId ?? data.classes[0]?.id ?? "");
  const activeClassId = data.openRun?.classId ?? selectedClassId;
  const students = data.students.filter(({ classId }) => classId === activeClassId);
  const [studentIndex, setStudentIndex] = useState(0); const student = students[studentIndex];

  useEffect(() => { if (!startedAt) return; const timer = window.setInterval(() => setSeconds((value) => value + 1), 1000); return () => window.clearInterval(timer); }, [startedAt]);

  async function start() {
    if (!activeClassId || students.length === 0) return;
    setBusy(true); setError(null);
    const scheduled = data.nextCourse?.classId === activeClassId ? data.nextCourse : null;
    const result = scheduled
      ? await createClient().rpc("teacher_start_session", { target_course_session_id: scheduled.id })
      : await createClient().rpc("teacher_start_class_session", { target_class_id: activeClassId });
    setBusy(false);
    if (result.error || !result.data) return setError("تعذر بدء الحصة. تحقق من الاتصال ثم حاول مجددًا.");
    setRunId(result.data); setStartedAt(new Date().toISOString()); setStep(1);
  }
  async function saveAttendance() { if (!runId) return; setBusy(true); setError(null); const rows = students.map(({ id }) => ({ student_id: id, status: attendance[id]?.status ?? "absent", minutes_late: attendance[id]?.minutesLate ?? 0 })); const result = await createClient().rpc("teacher_save_attendance", { target_run_id: runId, attendance_rows: rows }); setBusy(false); if (result.error) return setError("تعذر حفظ الحضور. لم يتم الانتقال."); setStep(2); setStudentIndex(0); }
  async function openReport() { if (!runId) return; setBusy(true); setError(null); const result = await createClient().rpc("teacher_open_session_report", { target_run_id: runId }); setBusy(false); if (result.error || !result.data) return setError("تعذر فتح تقرير الحصة."); setReportId(result.data); setStep(3); }
  async function cancelSession() { if (!runId || !window.confirm("هل أنت متأكد(ة) من إلغاء هذه الحصة؟")) return; if (!window.confirm("سيتم إلغاء الحصة الجارية. أكد(ي) مرة ثانية.")) return; setBusy(true); const result = await createClient().rpc("teacher_cancel_session", { target_run_id: runId }); setBusy(false); if (result.error) return setError("تعذر إلغاء الحصة."); router.replace("/teacher"); router.refresh(); }
  function leave() { if (runId && !window.confirm("الحصة محفوظة وما زالت جارية. هل تريد(ين) الخروج من الشاشة؟")) return; router.push("/teacher"); }

  return <div className="session-mode">
    <header className="session-top"><div><span>{formatDate(new Date())}</span><strong>{data.nextCourse?.className ?? data.classes.find(({ id }) => id === activeClassId)?.name ?? "الحصة"}</strong></div>{startedAt ? <div className="session-timer"><Clock3 size={17} /><span>البداية {formatTime(startedAt)}</span><strong>{formatDuration(seconds)}</strong></div> : null}<div className="session-top__actions">{runId ? <Button size="sm" variant="quiet" disabled={busy} onClick={() => void cancelSession()}>إلغاء الحصة</Button> : null}<Button size="sm" variant="quiet" onClick={leave}>خروج</Button></div></header>
    <div className="session-progress" aria-label={`الخطوة ${step + 1} من 4`}>{[0, 1, 2, 3].map((item) => <span key={item} className={item <= step ? "is-active" : undefined} />)}</div>
    {error ? <p className="session-error" role="alert"><AlertTriangle size={18} />{error}</p> : null}
    {step === 0 ? <StartStep data={data} classId={activeClassId} onClassChange={setSelectedClassId} busy={busy} onStart={() => void start()} /> : null}
    {step === 1 ? <AttendanceStep students={students} attendance={attendance} setAttendance={setAttendance} busy={busy} onContinue={() => void saveAttendance()} /> : null}
    {step === 2 && student ? <StudentStep key={student.id} runId={runId!} student={student} attendanceStatus={attendance[student.id]?.status ?? "absent"} position={studentIndex + 1} total={students.length} defaultDueDate={data.defaultDueDate} busy={busy} setBusy={setBusy} onError={setError} onMarkedLate={() => setAttendance((state) => ({ ...state, [student.id]: { status: "late", minutesLate: Math.max(1, state[student.id]?.minutesLate ?? 1) } }))} onWorked={() => setWorked((current) => new Set(current).add(student.id))} onBack={() => setStudentIndex((value) => Math.max(0, value - 1))} onNext={() => setStudentIndex((value) => Math.min(students.length - 1, value + 1))} onFinish={() => void openReport()} /> : null}
    {step === 3 && reportId ? <ReportStep reportId={reportId} students={students} attendance={attendance} worked={worked} busy={busy} setBusy={setBusy} onError={setError} onSubmitted={() => { showToast({ title: "تم إرسال تقرير الحصة", tone: "success" }); router.push("/teacher/professional?tab=reports"); router.refresh(); }} /> : null}
  </div>;
}

function StartStep({ data, classId, onClassChange, busy, onStart }: { data: TeacherSessionData; classId: string; onClassChange: (value: string) => void; busy: boolean; onStart: () => void }) {
  const selectedClass = data.classes.find(({ id }) => id === classId);
  const studentCount = data.students.filter((student) => student.classId === classId).length;
  const canStart = Boolean(data.teacher && selectedClass && studentCount > 0);
  const scheduled = data.nextCourse?.classId === classId ? data.nextCourse : null;
  return <section className="session-step session-start"><Badge tone="brand">الاستعداد</Badge><h1>هل أنت مستعد(ة) لبدء الحصة؟</h1>{data.classes.length > 1 ? <label className="session-class-picker">القسم<select aria-label="القسم" value={classId} onChange={(event) => onClassChange(event.target.value)}>{data.classes.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label> : null}<div className="session-brief"><div><span>الحصة</span><strong>{scheduled?.title ?? "حصة مباشرة"}</strong></div><div><span>القسم</span><strong>{selectedClass?.name ?? "—"}</strong></div><div><span>الطلاب</span><strong>{studentCount}</strong></div></div>{!data.teacher ? <p className="session-blocked" role="alert">تعذر التحقق من حساب الأستاذ(ة). أعد تسجيل الدخول.</p> : !selectedClass ? <p className="session-blocked" role="alert">لا يوجد قسم مسند إلى حسابك حاليا. تواصل(ي) مع الإدارة.</p> : studentCount === 0 ? <p className="session-blocked" role="alert">لا يوجد طلاب مسجلون في هذا القسم حاليا. تواصل(ي) مع الإدارة.</p> : null}<Button disabled={!canStart || busy} loading={busy} onClick={onStart}><Play size={18} />بدء الحصة</Button></section>;
}

function AttendanceStep({ students, attendance, setAttendance, busy, onContinue }: { students: TeacherSessionData["students"]; attendance: AttendanceState; setAttendance: Dispatch<SetStateAction<AttendanceState>>; busy: boolean; onContinue: () => void }) {
  const count = (status: DatabaseAttendanceStatus) => students.filter(({ id }) => attendance[id]?.status === status).length;
  return <section className="session-step"><div className="session-title"><div><span>الخطوة 2</span><h1>اختر الطلاب الحاضرين</h1></div><div className="attendance-counts"><b>{count("present")} حاضر</b><b>{count("absent")} غائب</b><b>{count("late")} متأخر</b></div></div><div className="attendance-list">{students.map((student) => { const current = attendance[student.id] ?? { status: "absent", minutesLate: 0 }; const present = current.status === "present" || current.status === "late"; return <article className={present ? "is-present" : undefined} key={student.id}><button className="attendance-person" type="button" aria-pressed={present} onClick={() => setAttendance((state) => ({ ...state, [student.id]: { status: present ? "absent" : "present", minutesLate: 0 } }))}><span className="teacher-avatar">{student.name.slice(0, 1)}</span><strong>{student.name}</strong><Check size={18} /></button><button className={current.status === "late" ? "late-toggle is-active" : "late-toggle"} type="button" onClick={() => setAttendance((state) => ({ ...state, [student.id]: { status: "late", minutesLate: Math.max(1, current.minutesLate) } }))}>متأخر</button>{current.status === "late" ? <input aria-label={`دقائق تأخر ${student.name}`} type="number" min="1" max="600" value={current.minutesLate} onChange={(event) => setAttendance((state) => ({ ...state, [student.id]: { status: "late", minutesLate: Number(event.target.value) } }))} /> : null}</article>; })}</div><div className="session-footer"><Button variant="quiet" onClick={() => history.back()}><ArrowRight size={17} />رجوع</Button><Button loading={busy} onClick={onContinue}><Check size={18} />تأكيد الحضور</Button></div></section>;
}

function StudentStep({ runId, student, attendanceStatus, position, total, defaultDueDate, busy, setBusy, onError, onMarkedLate, onWorked, onBack, onNext, onFinish }: { runId: string; student: TeacherSessionData["students"][number]; attendanceStatus: DatabaseAttendanceStatus; position: number; total: number; defaultDueDate: string; busy: boolean; setBusy: (value: boolean) => void; onError: (value: string | null) => void; onMarkedLate: () => void; onWorked: () => void; onBack: () => void; onNext: () => void; onFinish: () => void }) {
  const surahs = getAllSurahs(); const initialSurah = student.lastSurahNumber ?? 114;
  const [surah, setSurah] = useState(initialSurah); const [from, setFrom] = useState(1); const [to, setTo] = useState(getSurah(initialSurah)?.verseCount ?? 1);
  const [appreciation, setAppreciation] = useState<DatabaseRecitationAppreciation>("good"); const [comment, setComment] = useState(""); const [createAssignment, setCreateAssignment] = useState(false); const [due, setDue] = useState(defaultDueDate);
  function changeSurah(value: number) { setSurah(value); setFrom(1); setTo(getSurah(value)?.verseCount ?? 1); }
  async function save() { if (from < 1 || to < from) return onError("تحقق من أرقام الآيات."); if (createAssignment && !due) return onError("حدد موعد الواجب."); setBusy(true); onError(null); if (attendanceStatus === "absent") { const late = await createClient().rpc("teacher_save_attendance", { target_run_id: runId, attendance_rows: [{ student_id: student.id, status: "late", minutes_late: 1 }] }); if (late.error) { setBusy(false); return onError("تعذر تحديث حضور الطالب المتأخر."); } onMarkedLate(); } const result = await createClient().rpc("teacher_record_student_work", { target_run_id: runId, target_student_id: student.id, target_surah_number: surah, target_verse_from: from, target_verse_to: to, target_appreciation: appreciation, target_comment: comment, target_behavior: "good", target_difficulties: [], target_create_goal: false, target_goal_surah: surah, target_goal_from: from, target_goal_to: to, target_create_assignment: createAssignment, target_assignment_due: createAssignment ? new Date(`${due}T18:00:00`).toISOString() : null }); setBusy(false); if (result.error) return onError("تعذر حفظ القراءة. تحقق من البيانات والاتصال."); onWorked(); }
  const appreciationOptions: Array<[DatabaseRecitationAppreciation, string]> = [["excellent", "ممتاز"], ["very_good", "جيد جدا"], ["good", "جيد"], ["acceptable", "مقبول"], ["needs_review", "يحتاج مراجعة"], ["weak", "ضعيف"]];
  return <section className="session-step"><div className="student-session-head"><span className="teacher-avatar is-large">{student.name.slice(0, 1)}</span><div><small>الطالب {position} من {total} · {attendanceLabel(attendanceStatus)}</small><h1>{student.name}</h1><p>{student.className}</p></div></div><div className="student-insight"><span>آخر تقدم<strong>{student.lastSurahNumber ? getSurah(student.lastSurahNumber)?.nameArabic : "لا يوجد"}</strong></span><span>الغياب<strong>{student.absenceCount}</strong></span><span>واجبات<strong>{student.pendingAssignments}</strong></span></div><div className="assistant-note"><Flag size={18} /><span>{student.suggestion}</span></div><div className="quick-form"><label>السورة<select value={surah} onChange={(event) => changeSurah(Number(event.target.value))}>{surahs.map((item) => <option key={item.number} value={item.number}>{item.number} · {item.nameArabic}</option>)}</select></label><div className="form-pair"><label>من الآية<input type="number" min="1" value={from} onChange={(event) => setFrom(Number(event.target.value))} /></label><label>إلى الآية<input type="number" min="1" value={to} onChange={(event) => setTo(Number(event.target.value))} /></label></div><fieldset><legend>التقدير</legend><div className="choice-row">{appreciationOptions.map(([value, label]) => <button type="button" className={appreciation === value ? "is-active" : undefined} key={value} onClick={() => setAppreciation(value)}>{label}</button>)}</div></fieldset><label>ملاحظة اختيارية<input value={comment} maxLength={1000} onChange={(event) => setComment(event.target.value)} /></label><details className="session-extra"><summary>إضافة واجب</summary><label className="toggle-line"><input type="checkbox" checked={createAssignment} onChange={(event) => setCreateAssignment(event.target.checked)} />إرسال واجب مراجعة</label>{createAssignment ? <input aria-label="موعد الواجب" type="date" value={due} onChange={(event) => setDue(event.target.value)} /> : null}</details></div><div className="session-footer session-footer--wide"><Button variant="quiet" disabled={position === 1} onClick={onBack}><ArrowRight size={17} />السابق</Button><Button loading={busy} onClick={() => void save()}><Check size={17} />حفظ القراءة</Button><Button variant="secondary" disabled={position === total} onClick={onNext}>الطالب التالي<ArrowLeft size={17} /></Button><Button variant="quiet" onClick={onFinish}><StopCircle size={17} />إنهاء الحصة</Button></div></section>;
}

function ReportStep({ reportId, students, attendance, worked, busy, setBusy, onError, onSubmitted }: { reportId: string; students: TeacherSessionData["students"]; attendance: AttendanceState; worked: Set<string>; busy: boolean; setBusy: (value: boolean) => void; onError: (value: string | null) => void; onSubmitted: () => void }) {
  const [program, setProgram] = useState<"completed" | "partial" | "not_completed">("completed"); const [behavior, setBehavior] = useState<"excellent" | "good" | "mixed" | "difficult">("good"); const [flags, setFlags] = useState<string[]>([]); const [follow, setFollow] = useState<string[]>([]); const [incident, setIncident] = useState(false); const [incidentText, setIncidentText] = useState(""); const [equipment, setEquipment] = useState<"ready" | "missing" | "damaged">("ready"); const [equipmentText, setEquipmentText] = useState(""); const [note, setNote] = useState(""); const [preview, setPreview] = useState(false);
  const present = students.filter(({ id }) => attendance[id]?.status === "present").length; const absent = students.filter(({ id }) => attendance[id]?.status === "absent").length; const late = students.filter(({ id }) => attendance[id]?.status === "late").length; const notWorked = students.filter(({ id }) => ["present", "late"].includes(attendance[id]?.status ?? "absent") && !worked.has(id));
  async function submit() { setBusy(true); onError(null); const result = await createClient().rpc("teacher_submit_session_report", { target_report_id: reportId, target_program_status: program, target_behavior: behavior, target_difficulties: flags, target_follow_up_students: follow, target_incident: incident, target_incident_summary: incidentText, target_equipment: equipment, target_equipment_details: equipmentText, target_optional_note: note }); setBusy(false); if (result.error) return onError("تعذر إرسال التقرير."); onSubmitted(); }
  if (preview) return <section className="session-step"><Badge tone="success">المعاينة</Badge><h1>راجع تقرير الحصة</h1><div className="report-presence"><span>حاضر<strong>{present}</strong></span><span>غائب<strong>{absent}</strong></span><span>متأخر<strong>{late}</strong></span></div><div className="report-preview"><strong>الطلاب الذين تمت متابعتهم: {worked.size}</strong><p>حاضرون دون قراءة: {notWorked.map(({ name }) => name).join("، ") || "لا أحد"}</p><p>البرنامج: {programLabel(program)} · السلوك: {behaviorLabel(behavior)}</p></div><div className="session-footer"><Button variant="quiet" onClick={() => setPreview(false)}>تعديل</Button><Button loading={busy} onClick={() => void submit()}><Send size={18} />تأكيد وإرسال</Button></div></section>;
  return <section className="session-step"><Badge tone="success">الخطوة الأخيرة</Badge><h1>تقرير الحصة</h1><div className="report-presence"><span>حاضر<strong>{present}</strong></span><span>غائب<strong>{absent}</strong></span><span>متأخر<strong>{late}</strong></span></div><Choice label="البرنامج" value={program} onChange={setProgram} options={[["completed", "كامل"], ["partial", "جزئي"], ["not_completed", "لم ينجز"]]} /><Choice label="السلوك" value={behavior} onChange={setBehavior} options={[["excellent", "ممتاز"], ["good", "جيد"], ["mixed", "متفاوت"], ["difficult", "صعب"]]} /><details className="session-extra"><summary>تفاصيل إضافية</summary><fieldset><legend>الصعوبات</legend><div className="check-row">{difficulties.map((item) => <label key={item}><input type="checkbox" checked={flags.includes(item)} onChange={() => setFlags((current) => current.includes(item) ? current.filter((flag) => flag !== item) : [...current, item])} />{item}</label>)}</div></fieldset><fieldset><legend>طلاب يحتاجون متابعة</legend><div className="check-row">{students.map((item) => <label key={item.id}><input type="checkbox" checked={follow.includes(item.id)} onChange={() => setFollow((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id])} />{item.name}</label>)}</div></fieldset><label className="toggle-line"><input type="checkbox" checked={incident} onChange={(event) => setIncident(event.target.checked)} />حادث أو مشكل</label>{incident ? <label>وصف قصير<input value={incidentText} onChange={(event) => setIncidentText(event.target.value)} /></label> : null}<Choice label="المعدات" value={equipment} onChange={setEquipment} options={[["ready", "جاهزة"], ["missing", "ناقصة"], ["damaged", "متضررة"]]} />{equipment !== "ready" ? <label>تفصيل<input value={equipmentText} onChange={(event) => setEquipmentText(event.target.value)} /></label> : null}<label>ملاحظة اختيارية<input value={note} onChange={(event) => setNote(event.target.value)} /></label></details><Button disabled={incident && incidentText.trim().length < 3} onClick={() => setPreview(true)}>معاينة التقرير<ArrowLeft size={17} /></Button></section>;
}

function Choice<T extends string>({ label, value, onChange, options }: { label: string; value: T; onChange: (value: T) => void; options: Array<[T, string]> }) { return <fieldset><legend>{label}</legend><div className="choice-row">{options.map(([key, text]) => <button type="button" className={value === key ? "is-active" : undefined} key={key} onClick={() => onChange(key)}>{text}</button>)}</div></fieldset>; }
function attendanceLabel(value: string) { return ({ present: "حاضر", absent: "غائب", late: "متأخر", excused: "غياب مبرر" } as Record<string, string>)[value] ?? value; }
function programLabel(value: string) { return ({ completed: "كامل", partial: "جزئي", not_completed: "لم ينجز" } as Record<string, string>)[value] ?? value; }
function behaviorLabel(value: string) { return ({ excellent: "ممتاز", good: "جيد", mixed: "متفاوت", difficult: "صعب" } as Record<string, string>)[value] ?? value; }
function formatDuration(seconds: number) { const hours = Math.floor(seconds / 3600).toString().padStart(2, "0"); const minutes = Math.floor((seconds % 3600) / 60).toString().padStart(2, "0"); return `${hours}:${minutes}:${(seconds % 60).toString().padStart(2, "0")}`; }
function formatTime(value: string) { return new Intl.DateTimeFormat("ar-MA", { hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function formatDate(value: Date) { return new Intl.DateTimeFormat("ar-MA", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(value); }
