"use client";

import { Check, Gamepad2, Plus, Puzzle, RotateCcw, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button, useToast } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import { getAllSurahs } from "@/features/quran/canonical";
import { createQuranRound, isCorrect, type QuranGameKind, type QuranGameRound } from "@/features/games/engine";
import { JUZ } from "@/features/quran/quran-catalog";
import { applyAppearance, readAccent, readAppearance, saveAppearance } from "@/features/settings/appearance";
import type { AppearanceAccent, AppearanceMode } from "@/features/settings/appearance";
import { deviceAccountHome, readDeviceAccounts, rememberAuthenticatedAccount, removeDeviceAccount } from "@/features/teacher/device-account-vault";
import type { SavedDeviceAccount } from "@/features/teacher/device-account-vault";

export function StudentGames({ unlocked }: { unlocked: number[] }) {
  const games: Array<{ kind: QuranGameKind; title: string; text: string }> = [{ kind: "verse_order", title: "رتّب الآيات", text: "أعد بناء المقطع بالترتيب" }, { kind: "match_edges", title: "لغز المقطع", text: "صل البداية بالنهاية الصحيحة" }, { kind: "missing_word", title: "أكمل المقطع", text: "استرجع الكلمات الناقصة" }];
  const [kind, setKind] = useState<QuranGameKind | null>(null); const [juzNumber, setJuzNumber] = useState<number | null>(null); const [selected, setSelected] = useState<number[]>([]); const [roundIndex, setRoundIndex] = useState(0); const [round, setRound] = useState<QuranGameRound | null>(null); const [ordered, setOrdered] = useState<number[]>([]); const [score, setScore] = useState(0);
  const choices = getAllSurahs().filter((surah) => unlocked.includes(surah.number)).reverse();
  if (!choices.length) return <section className="student-empty"><Gamepad2 size={30} /><strong>أتم سورة واحدة لفتح الألعاب</strong></section>;
  const accessibleJuz = JUZ.filter((juz) => choices.some((surah) => surah.number >= juz.from && surah.number <= juz.to));
  const selectedJuz = JUZ.find((juz) => juz.number === juzNumber);
  const juzSurahs = choices.filter((surah) => selectedJuz && surah.number >= selectedJuz.from && surah.number <= selectedJuz.to);
  function nextRound(index: number): QuranGameRound | null { const surah = choices.find((item) => item.number === selected[index % selected.length]); return surah && kind ? createQuranRound(surah, kind, index) : null; }
  function begin() { setRoundIndex(0); setScore(0); setOrdered([]); setRound(nextRound(0)); }
  function answer(value: string) { if (!round) return; setScore((current) => current + (isCorrect(round, value) ? 1 : 0)); const next = roundIndex + 1; if (next >= Math.max(3, selected.length)) { setRound(null); setRoundIndex(-1); return; } setRoundIndex(next); setOrdered([]); setRound(nextRound(next)); }
  return <div className="student-games"><header className="student-page-head"><h1>ألعاب القرآن</h1></header>{!kind ? <section className="student-game-portal">{games.map((game) => <button key={game.kind} onClick={() => setKind(game.kind)}><Puzzle aria-hidden="true" /><strong>{game.title}</strong><span>{game.text}</span></button>)}</section> : !juzNumber ? <section className="student-game-picker"><h2>اختر الجزء</h2><div>{accessibleJuz.map((juz) => <button key={juz.number} onClick={() => setJuzNumber(juz.number)}>{juz.name}</button>)}</div></section> : !round && roundIndex >= 0 ? <section className="student-game-picker"><h2>اختر سورة أو أكثر</h2><div>{juzSurahs.map((surah) => <button key={surah.number} className={selected.includes(surah.number) ? "is-selected" : ""} onClick={() => setSelected((value) => value.includes(surah.number) ? value.filter((id) => id !== surah.number) : [...value, surah.number])}><span>{surah.nameArabic}</span>{selected.includes(surah.number) ? <Check size={16} /> : null}</button>)}</div><Button disabled={!selected.length} onClick={begin}>ابدأ اللعبة</Button></section> : round ? <section className="student-game-board"><span>الجولة {roundIndex + 1}</span><p>{round.prompt}</p>{round.kind === "verse_order" ? <><div className="learning-word-answer">{ordered.map((index, position) => <button key={position} onClick={() => setOrdered((value) => value.filter((_, item) => item !== position))}>{round.options[index]}</button>)}</div><div className="learning-word-bank">{round.options.map((option, index) => <button key={index} disabled={ordered.includes(index)} onClick={() => setOrdered((value) => [...value, index])}>{option}</button>)}</div><Button disabled={ordered.length !== round.options.length} onClick={() => answer(ordered.map((index) => round.options[index]).join(" "))}>تحقق</Button></> : <div className="student-exercise__options">{round.options.map((option) => <button key={option} onClick={() => answer(option)}>{option}</button>)}</div>}</section> : <section className="student-game-board"><h2>النتيجة {score}/{Math.max(3, selected.length)}</h2><Button onClick={begin}><RotateCcw size={17} />إعادة اللعب</Button><Button variant="quiet" onClick={() => { setKind(null); setJuzNumber(null); setSelected([]); setRoundIndex(0); setScore(0); }}>الألعاب</Button></section>}</div>;
}

export function ParentSurvey() {
  const { showToast } = useToast(); const [scores, setScores] = useState<number[]>([0, 0, 0, 0, 0]); const [comment, setComment] = useState(""); const [sending, setSending] = useState(false);
  async function send() { if (scores.some((score) => !score)) return showToast({ title: "اختر درجة لكل معيار" }); setSending(true); const { error } = await createClient().rpc("submit_parent_feedback", { target_scores: scores, target_comment: comment.trim() || null }); setSending(false); if (error) showToast({ title: "تعذر الإرسال", description: "حاول مرة أخرى." }); else { setComment(""); setScores([0, 0, 0, 0, 0]); showToast({ title: "شكراً، تم إرسال رأيكم", tone: "success" }); } }
  return <div className="student-parent"><header className="student-page-head"><h1>للـوالدين</h1></header><section className="parent-survey"><h2>استبيان المتابعة</h2>{["التنظيم", "المنهج التربوي", "التعليم", "سهولة استعمال المنصة", "أوقات الحصص"].map((label, index) => <fieldset key={label}><legend>{label}{scores[index] ? <strong>{scores[index]}/10</strong> : null}</legend><div className="parent-score-grid">{Array.from({ length: 10 }, (_, value) => value + 1).map((score) => <button type="button" aria-pressed={scores[index] === score} className={scores[index] === score ? "is-selected" : ""} key={score} onClick={() => setScores((values) => values.map((item, position) => position === index ? score : item))}>{score}</button>)}</div></fieldset>)}<textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="ملاحظة اختيارية" /><Button loading={sending} onClick={() => void send()}>إرسال</Button></section></div>;
}

export function StudentSettings() {
  const router = useRouter(); const { showToast } = useToast(); const [appearance, setAppearance] = useState<AppearanceMode>(readAppearance); const [accent, setAccent] = useState<AppearanceAccent>(readAccent); const [accounts, setAccounts] = useState<SavedDeviceAccount[]>([]); const [active, setActive] = useState<string | null>(null);
  useEffect(() => { void rememberAuthenticatedAccount().then(({ items, active: id }) => { setAccounts(items); setActive(id); }); }, []);
  function change(mode: AppearanceMode, color = accent) { setAppearance(mode); setAccent(color); saveAppearance(mode, color); applyAppearance(mode, color); }
  async function switchTo(account: SavedDeviceAccount) { const { data, error } = await createClient().auth.setSession({ access_token: account.accessToken, refresh_token: account.refreshToken }); if (error || !data.session || data.session.user.id !== account.id) return showToast({ title: "إعادة الاتصال مطلوبة" }); const remembered = await rememberAuthenticatedAccount(); setAccounts(remembered.items); setActive(remembered.active); router.replace(deviceAccountHome(account.kind)); router.refresh(); }
  return <div className="student-settings"><header className="student-page-head"><h1>الإعدادات</h1></header><section><h2>المظهر</h2><div className="student-setting-row">{(["light", "dark", "system"] as AppearanceMode[]).map((mode) => <button className={appearance === mode ? "is-active" : ""} key={mode} onClick={() => change(mode)}>{({ light: "فاتح", dark: "داكن", system: "حسب الجهاز" })[mode]}</button>)}</div><div className="student-color-row">{(["green", "blue", "plum", "gold"] as AppearanceAccent[]).map((color) => <button key={color} className={`is-${color} ${accent === color ? "is-active" : ""}`} aria-label={color} onClick={() => change(appearance, color)} />)}</div></section><section><h2>الحسابات على هذا الجهاز</h2>{accounts.map((account) => <article className="student-account" key={account.id}><span>{account.name}</span>{account.id === active ? <small>الحساب الحالي</small> : <Button size="sm" variant="secondary" onClick={() => void switchTo(account)}>تبديل</Button>}<button aria-label="إزالة الحساب من هذا الجهاز" onClick={() => { removeDeviceAccount(account.id); setAccounts(readDeviceAccounts()); }}><Trash2 size={17} /></button></article>)}<Button variant="secondary" onClick={() => router.push("/login?add=1")}><Plus size={18} />إضافة حساب</Button></section></div>;
}

export function StudentProfile({ name, dateOfBirth, className, documents, file }: { name: string; dateOfBirth: string | null; className: string | null; documents: Array<{ id: string; title: string; category: string; path: string }>; file: { birth: boolean; guardian: boolean; identity: boolean; paymentRequired: boolean; fee: number | null; payments: Array<{ month: string; amount: number; date: string }> } | null }) {
  const today = new Date(); const startYear = today.getMonth() >= 8 ? today.getFullYear() : today.getFullYear() - 1; const months = Array.from({ length: 10 }, (_, index) => { const date = new Date(startYear, 8 + index, 1); return { key: date.toISOString().slice(0, 7), label: new Intl.DateTimeFormat("ar-MA", { month: "long" }).format(date) }; });
  return <div className="student-profile"><header className="student-page-head"><h1>ملفي</h1></header><section><h2>{name}</h2><div className="student-profile-lines"><p><span>القسم</span><strong>{className ?? "—"}</strong></p><p><span>تاريخ الازدياد</span><strong>{dateOfBirth ?? "—"}</strong></p></div></section><section><h2>وثائق التسجيل</h2><Status label="عقد الازدياد" value={file?.birth ?? false} /><Status label="هوية ولي الأمر" value={file?.guardian ?? false} /><Status label="هوية التلميذ" value={file?.identity ?? false} />{documents.map((document) => <a key={document.id} href={document.path} target="_blank" rel="noreferrer">{document.title}</a>)}</section><section><h2>الواجبات</h2><p className="student-payment">{file?.paymentRequired === false ? "معفى من الأداء" : file?.fee ? `${file.fee} درهم شهرياً` : "تحدده الإدارة"}</p><div className="student-months">{months.map((month) => { const payment = file?.payments.find((item) => item.month === month.key); return <details key={month.key} className={payment ? "is-paid" : ""}><summary>{month.label}<strong>{payment ? "مؤدى" : "غير مؤدى"}</strong></summary>{payment ? <p>{payment.amount} درهم · {payment.date}</p> : <p>في انتظار تأكيد الإدارة</p>}</details>; })}</div></section></div>;
}
function Status({ label, value }: { label: string; value: boolean }) { return <p className="student-status"><span>{label}</span><strong className={value ? "is-yes" : "is-no"}>{value ? "تم" : "غير مسلّم"}</strong></p>; }
