import { notFound } from "next/navigation";
import { AppShell } from "@/components/shell";
import { Badge, ButtonLink, EmptyState } from "@/components/ui";
import { AccountStatusControls } from "@/features/admin/account-status-controls";
import { getAdminCommandData } from "@/features/admin/repository";

export const dynamic = "force-dynamic";
export default async function PersonPage({ params }: { params: Promise<{ personId: string }> }) {
  const { personId } = await params; const data = await getAdminCommandData(); const person = data.people.find(({ id }) => id === personId); if (!person) notFound(); const events = data.timeline.filter((item) => item.title.startsWith(person.name));
  return <AppShell kind="admin"><div className="command-page"><header className="person-file-header"><span className="person-file-avatar">{person.name.slice(0, 1)}</span><div><span>الملف الرقمي</span><h1>{person.name}</h1><p>{person.className ?? "لا يوجد قسم مرتبط"}</p></div><div className="person-file-controls"><Badge tone={person.status === "active" ? "success" : "warning"}>{person.status}</Badge><AccountStatusControls userId={person.id} schoolId={data.school?.id ?? null} status={person.status} /></div></header><nav className="file-tabs"><a href="#overview">نظرة عامة</a><a href="#learning">التعلم</a><a href="#attendance">الحضور</a><a href="#history">التاريخ</a><a href="#documents">الوثائق</a></nav><section className="person-file-stats" id="overview"><article><span>السور المكتملة</span><strong>{person.mastered}</strong></article><article><span>الغياب المسجل</span><strong>{person.absences}</strong></article><article><span>التأخر المسجل</span><strong>{person.late}</strong></article><article><span>العمر</span><strong>{person.age ?? "—"}</strong></article></section><section className="command-panel" id="history"><div className="command-heading"><h2>الخط الزمني</h2><ButtonLink href="/admin/people" variant="quiet">العودة</ButtonLink></div>{events.length ? <div className="command-timeline">{events.map((item) => <article key={item.id}><div><strong>{item.title}</strong><small>{item.detail}</small></div><time>{new Intl.DateTimeFormat("ar-MA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.occurredAt))}</time></article>)}</div> : <EmptyState title="لا يوجد تاريخ مسجل" description="ستظهر أنشطة الحساب المصرح بها هنا." />}</section></div></AppShell>;
}
